{{- $top := . -}}
{{- $values := .Values -}}
{{- if $values.configmap.data }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    {{- $defaultt := pick .Values.defaults.configmap "annotations" -}}
    {{- $ext := pick .Values.configmap "annotations" -}}
    {{- $res := mergeOverwrite $defaultt $ext -}}
    {{- toYaml $res.annotations | nindent 4 }}
  name: {{ include "name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  {{- range $key,$value := $values.configmap.data }}
  {{ tpl $key $ }}: {{ tpl $value $ | quote }}
  {{- end }}
{{- end }}