{{- $values := .Values -}}
{{- $top := . -}}
{{- range $jobName, $job := $values.cronjobs }}
{{- if $job.enabled }}
{{- $defaultSyncWave := true }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "name" $top }}-{{ $jobName }}
  labels:
    {{- include "cronjob.labels" $top | nindent 4 }}
    app.kubernetes.io/component: {{ $jobName }}
  {{- if $job.metadata }}
  {{- with $job.metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  schedule: {{ required "when? what? how? $job.schedule is required" $job.schedule | quote }}
  {{- with $job.concurrencyPolicy }}
  concurrencyPolicy: {{ . }}
  {{- end }}
  {{- with $job.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with $job.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with $job.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ . }}
  {{- end }}
  jobTemplate:
    spec:
      {{- with $job.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ . }}
      {{- end }}
      backoffLimit: {{ $job.backoffLimit | default 1 }}
      template:
        metadata:
          labels:
            {{- include "job.labels" $top | nindent 12 }}
            app.kubernetes.io/component: {{ $jobName }}
        {{- with $job.annotations }}
        annotations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        spec:
          {{- if $values.serviceAccount.enabled }}
          serviceAccountName: {{ include "service.account.name" $top }}
          {{- end }}
          {{- with $job.nodeSelector }}
          nodeSelector:
          {{ toYaml . | indent 2 }}
          {{- end }}
          {{- with $values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or $values.externalSecret.enabled $job.additionalVolumes }}
          volumes:
            {{- if $values.externalSecret.enabled }}
            - name: secret-volume
              secret:
                secretName: {{ include "secret.name" $ }}
            {{- end }}
            {{- with $job.additionalVolumes }}
            {{- tpl . $top | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with $job.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ include "container.name" $top }}
              {{- if $job.image }}
              image: {{ $job.image | quote }}
              {{- else }}
              image: "{{ $values.image.repository }}:{{ $values.appVersion }}"
              {{- end }}
              imagePullPolicy: {{ $values.imagePullPolicy }}
              {{- if or $values.externalSecret.enabled $job.additionalVolumeMounts }}
              volumeMounts:
                {{- if $values.externalSecret.enabled }}
                {{- include "externalsecret.volumemount" $ | nindent 16 }}
                {{- end }}
                {{- with $job.additionalVolumeMounts }}
                {{- tpl . $top | nindent 16  }}
                {{- end }}
              {{- end }}
              {{- with $job.resources}}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
              {{- if $values.externalSecret.enabled }}
                - name: FRONTEGG_CONFIG_DIRECTORY
                  value: "/etc/config"
              {{- end }}
              {{- range $config_name, $values := $values.configuration.map }}
              {{- range $key, $value :=  $values}}
                - name: {{ $key }}
                  valueFrom:
                    configMapKeyRef:
                      name: {{ $config_name }}
                      key: {{ $value }}
              {{- end }}
              {{- end }}
              {{- if $values.configmap.data }}
              envFrom:
                - configMapRef:
                    name: {{ include "name" $top }}
              {{- end }}
              {{- with $job.command }}
              command:
                {{- range . }}
                - {{ tpl . $ | quote  }}
                {{- end }}
              {{- end }}
              {{- with $job.args }}
              args:
                {{- range . }}
                - {{ . | quote  }}
                {{- end }}
              {{- end }}
          {{- with $job.affinity }}
          affinity:
          {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $job.tolerations }}
          tolerations:
          {{ toYaml . | indent 12 }}
          {{- end }}
          restartPolicy: {{ $job.restartPolicy | default "Never" }}
{{- end }}
{{- end }}