{{- $values := .Values }}
{{- $top := . }}
{{- range $jobName, $job := $values.jobs }}
{{- if $job.enabled }}
{{- $res := dict }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "name" $top }}-{{ $jobName }}
  labels:
    {{- include "job.labels" $top | nindent 4 }}
    app.kubernetes.io/component: {{ $jobName }}
  annotations:
    {{- $mgr_ants := $values.defaults.migration.annotations }}
    {{- if $job.metadata }}
    {{- $job_ants := $job.metadata.annotations }}
    {{- $new_ants := merge $job_ants $mgr_ants }}
    {{- toYaml $new_ants | nindent 4 }}
    {{- else }}
    {{- toYaml $values.defaults.migration.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- with $job.spec }}
  ttlSecondsAfterFinished: {{ .ttlSecondsAfterFinished | default 6000 }}
  completions: {{ .completions | default 1 }}
  parallelism: {{ .parallelism | default 1 }}
  backoffLimit: {{ .backoffLimit | default 1 }}
  podReplacementPolicy: {{ .podReplacementPolicy | default "Failed" }}
  template:
    metadata:
      name: {{ include "name" $top | trunc 10 }}-{{ $jobName | trunc 10 }}-{{ $values.appVersion | trunc 41 }}
      labels:
        {{- include "job.labels" $top | nindent 8 }}
        app.kubernetes.io/component: {{ $jobName }}
      {{- with .annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if $values.serviceAccount.enabled }}
      serviceAccountName: {{ include "service.account.name" $top }}
      {{- end }}
      restartPolicy: {{ .restartPolicy | default "Never" }}
      {{- with $values.imagePullSecrets }}
      imagePullSecrets :
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or $values.externalSecret.enabled .additionalVolumes }}
      volumes:
        {{- if $values.externalSecret.enabled }}
        - name: secret-volume
          secret:
            secretName: {{ include "secret.name" $ }}
        {{- end }}
        {{- with .additionalVolumes }}
        {{- tpl . $top | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ include "container.name" $top }}
          {{- if $job.spec.image }}
          image: {{ $job.spec.image | quote }}
          {{- else }}
          image: "{{ $values.image.prefix }}{{ $values.image.repository }}:{{ $values.appVersion }}"
          {{- end }}
          {{- if or $values.externalSecret.enabled .additionalVolumeMounts }}
          volumeMounts:
            {{- if $values.externalSecret.enabled }}
            {{- include "externalsecret.volumemount" $ | nindent 12 }}
            {{- end }}
            {{- with .additionalVolumeMounts }}
            {{- tpl . $top | nindent 12 }}
            {{- end }}
          {{- end }}
          env:
            {{- include "container.env" . | indent 12 -}}
            {{- range $config_name, $localValues := $values.configuration.map }}
            {{- range $key, $value :=  $localValues }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $config_name }}
                  key: {{ $value }}
            {{- end }}
            {{- end }}
          {{- if $values.configmap.data }}
          envFrom:
            - configMapRef:
                name: {{ include "name" $top }}
          {{- end }}
          command:
            {{- range .command }}
            - {{ . | quote  }}
            {{- end }}
          args:
            {{- range .args }}
            - {{ . | quote  }}
            {{- end }}
          resources:
            {{- if .resources }}
            {{- toYaml .resources | nindent 12 }}
            {{- else }}
            {{- toYaml $values.defaults.migration.resources | nindent 12 }}
            {{- end }}
      {{- if $values.nodeSelector }}
      nodeSelector:
      {{- toYaml $values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $values.tolerations }}
      tolerations:
      {{- toYaml $values.tolerations | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
