{{- $top := . }}
{{- if (eq (include "isLinkerdInjectEnabled" .Values.web ) "true") }}
{{- if .Values.highPriority.serviceProfile }}
{{- with .Values.highPriority.serviceProfile.routes }}
---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: frontegg-{{ include "fuc.name" $top }}-service-hp.frontegg.svc.cluster.local
  namespace: frontegg
spec:
  routes:
    {{- . | toYaml | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}