{{- if (eq (include "isLinkerdInjectEnabled" .Values) "true") }}
---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: frontegg-{{ include "fuc.name" . }}.frontegg.svc.cluster.local
  namespace: frontegg
spec:
  routes:
    {{- if .Values.serviceProfile }}
    {{- with .Values.serviceProfile.routes }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
    {{- end }}
{{- end }}