apiVersion: v2
name: frontegg-core-services
description: Frontegg Core Services Helm Chart
type: application

version: 0.0.1-alpha.2
appVersion: 2025.06

maintainers:
  - name: "Frontegg"
    email: "support@frontegg.com"

dependencies:
  - name: &chartName unified-chart-staging
    version: &chartVersion 4.0.111
    repository: https://frontegg.github.io/helm-charts
    alias: admins

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: api-gateway

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: applications-service

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: authentication-service

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: audits-service

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: backoffice-service

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: dashboard-env-builder

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: directory-service

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: entitlements-service

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: env-duplicator

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: event-service

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: identity-service

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: forward-proxy

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: logs-service

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: metadata-service

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: oauth-service

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: prehook-service

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: security-center-service

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: security-engines

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: team-management-service

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: tenants-service

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: vendors-service

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: webhooks

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: task-master

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: entitlements-agent

  - name: *chartName
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: email-service

  - name: strimzi-kafka-operator
    version: 0.45.*
    repository: oci://quay.io/strimzi-helm
    condition: debezium.kafkaConnect.install

  - name: debezium-operator
    version: "3.1.0-final"
    repository: https://charts.debezium.io
    condition: debezium.debeziumOperator.install
