{{- $values := .Values -}}
{{- if $values.web.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.name" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
    {{- include "fail.if.empty" $values.web.service }}
    {{- with $values.web.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if $values.web.service.scrape }}
    {{- include "scrape.labels" . | nindent 4 }}
    {{- end }}
spec:
  type: {{ $values.web.service.type }}
  ports:
    {{- include "validate.ports" $values.web.service }}
    {{- range $values.web.service.ports }}
    - port: {{ required ".Values.web.service.ports[*].port number is required" .port }}
      targetPort: {{ required "need to know if someone listening: .Values.web.service.ports[*].targetPort is required" .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name | default "http" }}
    {{- end }}
  {{- if not $values.argoRollouts.progressiveDelivery.enabled }}
  selector:
    {{- include "web.selector.labels" . | nindent 4 }}
  {{- end }}
{{- end }}