{{- $top := . }}
{{- $values := .Values }}
{{- if .Values.linkerd.enabled }}
{{- with .Values.web.serviceProfile }}
{{- if .enabled }}
---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  {{- if $values.argoRollouts.progressiveDelivery.enabled }}
  name: {{ include "web.name" $top }}-stable.frontegg.svc.cluster.local
  {{- else }}
  name: {{ include "web.name" $top }}.frontegg.svc.cluster.local
  {{- end }}
  namespace: {{ .namespace | default "frontegg" }}
spec:
  routes:
    {{- .routes | toYaml | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
