{{- if .Values.web.enabled -}}
{{- if .Values.argoRollouts.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "web.name" . }}
spec:
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "web.name" . }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "web.selector.labels" . | nindent 6 }}
  strategy:
    blueGreen:
      {{- with .Values.argoRollouts.activeMetadata }}
      activeMetadata:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      activeService: {{ include "web.name" . }}
      autoPromotionEnabled: true
{{- end }}
{{- end }}