{{- $top := . -}}
{{- $values := .Values -}}
{{- if .Values.web.enabled -}}
{{- if .Values.argoRollouts.progressiveDelivery.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "web.name" $top }}
spec:
  parentRefs:
    {{- range $values.web.service.ports }}
    - group: "core"
      name: {{ include "web.name" $top  }}
      kind: Service
      port: {{ required ".Values.web.service.ports[*].port number is required" .port }}
    {{- end }}
  rules:
    - backendRefs:
    {{- range $type := tuple "canary" "stable" }}
          {{- range $values.web.service.ports }}
        - name: {{ include "web.name" $top  }}-{{ $type }}
          group: "core"
          port: {{ required ".Values.web.service.ports[*].port number is required" .port }}
          kind: Service
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
