{{ $values := .Values }}
{{- $debezium := $values.debezium }}
{{- $top := $ }}
{{- if $values.debezium.enabled }}
{{- if $values.debezium.kafkaConnect.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connector-configuration-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: [{{ .Values.initDbJob.secret.name | quote }}]
  verbs: ["get"]
{{- end }}
{{- end }}