{{- if .Values.externalSecret.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "external-secret-unique-name" . }}
  annotations:
    {{- with .Values.externalSecret.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  labels:
    {{- include "fuc.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: external-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ include "external-secret-unique-name" . }}
    template:
      engineVersion: v2
      data:
        config: |
          {{- .Values.externalSecret.text | toString | nindent 10 }}
          {{- with .Values.externalSecret.additionalSecrets }}
          {{- . | toString | nindent 10 }}
          {{- end }}
  data:
    - secretKey: contents
      remoteRef:
        conversionStrategy: {{ .Values.externalSecret.conversionStrategy | default "Default" }}	
        decodingStrategy: {{ .Values.externalSecret.decodingStrategy | default "None" }}
        key: {{ .Values.envID }}
  {{- end }}