{{- if .Values.offline.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webhook-service.fullname" . }}-offline-deployment
  labels:
    {{- include "webhook-service.offlineLabels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas : {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "webhook-service.offlineLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.frontegg.com/appVersion: {{ .Values.appVersion | quote }}
        {{- include "webhook-service.offlineLabels" . | nindent 8 }}
      annotations:
        checksum/secret: {{ (print .Values.secret) | sha256sum }}
        checksum/config: {{ (print .Values.configmap) | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.appVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }} # change this to 80 in the future
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.offline.enabled }}
            - name: FRONTEGG_IS_SERVICE_OFFLINE_PROCESS
              value: "true"
            {{- end  }}
            {{- range $secret_name, $values := .Values.configuration.secrets }}
            {{- range $key, $value :=  $values}}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret_name }}
                  key: {{ $value }}
            {{- end }}
            {{- end }}
            {{- range $config_name, $values := .Values.configuration.map }}
            {{- range $key, $value :=  $values}}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $config_name }}
                  key: {{ $value }}
          {{- end }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "webhook-service.fullname" . }}-configmap
            - secretRef:
                name: {{ include "webhook-service.fullname" . }}-secret
          resources:
            {{- toYaml .Values.offline.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
