{{- if .Values.externalSecret }}
{{- if .Values.externalSecret.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "external-secret-unique-name" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1000"
  labels:
  {{- include "tenants-service.labels" . | nindent 4 }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: external-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ include "external-secret-unique-name" . }}
    template:
      engineVersion: v2
      data:
        config: |
          {{- .Values.externalSecret.text | toString | nindent 10 }}
          {{- with .Values.externalSecret.additionalSecrets }}
          {{- . | toString | nindent 10 }}
          {{- end }}
  data:
    - secretKey: contents
      remoteRef:
        key: {{ .Values.componentsCollectionIdentifier }}
  {{- end }}
  {{- end }}
