{{- if .Values.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "fuc.fullname" . }}-hpa
  labels:
  {{- include "fuc.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    {{- if .Values.argoRollouts }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ include "fuc.fullname" . }}-rollout
    {{- else }}
    apiVersion : apps/v1
    kind : Deployment
    name : {{ include "fuc.fullname" . }}-deployment
    {{- end }}
  minReplicas: {{ (index .Values.minReplicasOverride .Values.componentsCollectionIdentifier).minReplicas | default .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
