{{- $top := . -}}
{{- $values := .Values -}}
{{- range $store := $values.clusterSecretStores }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ $store.name }}
  namespace: {{ $store.namespace | default "default" }}
  labels:
    {{- range $key, $value := $store.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  annotations:
    {{- range $key, $value := $store.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  provider:
    {{- tpl ($store.provider | toYaml) $top | nindent 4 }}
{{- end }}
