{{- if .Values.ingress.mcpGw.enabled -}}
{{- $fullName := include "fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-gw-ingress
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-gw
  {{- with .Values.ingress.mcpGw.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.mcpGw.ingressClassName }}
  ingressClassName: {{ . | quote }}
  {{- end }}
{{- if .Values.ingress.mcpGw.tls.enabled }}
  tls:
    - hosts:
        - {{ include "mcpGwHostname" . | quote }}
      secretName: {{ .Values.ingress.mcpGw.tls.secretName }}
{{- end }}
  rules:
    - host: {{ include "mcpGwHostname" . | quote }}
      http:
        paths:
        - path: /
          backend:
            service:
              name: {{ $fullName }}-gw
              port:
                number: 8080
          pathType: ImplementationSpecific
{{- end }}
