apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-auth
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-auth
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.mcpAuth.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-auth
