{{- $values := .Values -}}
{{- $top := . -}}
{{- range $block_name, $block_specs := $values.blocks -}}
{{- if $block_specs.deployment }}
{{- $deploy_specs := $block_specs.deployment }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $values.name }}-{{ $block_name }}-deployment
  labels:
    app.kubernetes.io/name: {{ $values.name }}-{{ $block_name }}-deployment
    {{- with $block_specs.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  {{- if not $block_specs.hpa }}
  replicas: {{ $deploy_specs.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $values.name }}-{{ $block_name }}-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $values.name }}-{{ $block_name }}-deployment
    spec:
      imagePullSecrets:
        {{- $deploy_specs.imagePullSecrets | default $values.defaults.deployment.imagePullSecrets | toYaml | nindent 8 }}
      {{- if false}}
      serviceAccountName: {{ include "common.serviceAccountName" $top }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $top.Chart.Name }}
          {{- if false}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          {{- $image := $deploy_specs.image | default $values.defaults.deployment.image }}
          {{- $appVersion := default $deploy_specs.appVersion $values.defaults.deployment.image.appVersion }}
          image: "{{ $image.repository }}:{{ $appVersion | default "master-latest" }}"
          imagePullPolicy: {{ $image.pullPolicy | default "always" }}
          {{- $ports := $deploy_specs.ports | default $values.defaults.deployment.ports }}
          {{- with $ports}}
          ports: 
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- $probes := $deploy_specs.probes | default $values.defaults.deployment.probes }}
          {{- with $probes }}
          {{- . | toYaml | nindent 10 }}
          {{- end }}
          {{- $resources := $deploy_specs.resources | default $values.defaults.deployment.resources }}
          {{- with $resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if false}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}     
{{- end }}
{{- end }}