{{- $top := . }}
{{- if .Values.rolebinding.enabled }}
{{- with .Values.rolebinding }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "name" $top }}
  namespace: {{ required "rolebinding.namespace requried" .namespace }}
  labels:
    {{- include "labels" $top | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "name" $top }}
subjects:
  - kind: ServiceAccount
    name: {{ include "name" $top }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}