{{- $top := . }}
{{- if .Values.role.enabled }}
{{- with .Values.role }}
{{- $rolekind := (.kind | lower) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ required ".Values.role.kind" $rolekind }}
metadata:
  name: {{ include "name" $top }}
  {{- if eq $rolekind "role" }}
  namespace: {{ required "role.namespace requried" .namespace }}
  {{- end }}
  {{- with .anotations }}
  annotations:
    {{- toYaml . | nindent }}
  {{- end }}
  labels:
    {{- include "labels" $top | nindent 4 }}
rules:
  {{- toYaml .rules | nindent 2 }}
{{- end }}  
{{- end }}