{{- if .Values.serviceAccount.enabled -}}
{{- if not .Values.serviceAccount.nameOverride }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    {{- $defaultAnnotations := pick .Values.default.sereviceAccount "annotations" -}}
    {{- $additionalAnnotations := pick .Values.serviceAccount "annotations" -}}
    {{- $annotations := mergeOverwrite $defaultAnnotations $additionalAnnotations -}}
    {{- toYaml $annotations.annotations | nindent 4 }}
{{- end }}
{{- end }}