{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service.account.name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    {{- $defaultAnnotations := pick .Values.defaults.sereviceAccount "annotations" -}}
    {{- $additionalAnnotations := pick .Values.serviceAccount "annotations" -}}
    {{- $annotations := mergeOverwrite $defaultAnnotations $additionalAnnotations -}}
    {{- toYaml $annotations.annotations | nindent 4 }}
{{- end }}