apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "messagepit.fullname" . }}
  labels:
    {{- include "messagepit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "messagepit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "messagepit.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "messagepit.serviceAccountName" . }}
      automountServiceAccountToken: false
      enableServiceLinks: false
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: messagepit
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --twilio=
            - --webhook=
            - --pop3=
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: ui
              containerPort: 8025
              protocol: TCP
            - name: sendgrid
              containerPort: 8100
              protocol: TCP
          env:
            - name: MP_SENDGRID_BIND_ADDR
              value: "0.0.0.0:8100"
            - name: MP_SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "messagepit.secretName" . }}
                  key: MP_SENDGRID_API_KEY
            - name: MP_UI_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ include "messagepit.secretName" . }}
                  key: MP_UI_AUTH
            - name: MP_MAX_AGE
              value: {{ .Values.retention.maxAge | quote }}
            - name: MP_MAX_MESSAGES
              value: {{ .Values.retention.maxMessages | quote }}
            - name: MP_DISABLE_VERSION_CHECK
              value: "true"
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
