{{- if .Values.externalSecret.enabled }}
{{- $remoteKey := default .Values.componentsCollectionIdentifier .Values.externalSecret.remoteKey }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "messagepit.fullname" . }}
  labels:
    {{- include "messagepit.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "messagepit.secretName" . }}
    creationPolicy: {{ .Values.externalSecret.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecret.deletionPolicy }}
    template:
      engineVersion: v2
      data:
        MP_SENDGRID_API_KEY: '{{ `{{- $secret := .contents | fromYaml -}}{{ $secret.externalServices.messagepit.sendgridApiKey }}` }}'
        MP_UI_AUTH: '{{ `{{- $secret := .contents | fromYaml -}}{{ printf "%s:%s" $secret.externalServices.messagepit.inboxUsername $secret.externalServices.messagepit.inboxPassword }}` }}'
  data:
    - secretKey: contents
      remoteRef:
        key: {{ required "externalSecret.remoteKey or componentsCollectionIdentifier is required" $remoteKey }}
{{- end }}
