{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "messagepit.secretName" . }}
  labels:
    {{- include "messagepit.labels" . | nindent 4 }}
type: Opaque
stringData:
  MP_SENDGRID_API_KEY: {{ required "sendgrid.apiKey is required when existingSecret is empty" .Values.sendgrid.apiKey | quote }}
  MP_UI_AUTH: {{ required "ui.auth is required when existingSecret is empty" .Values.ui.auth | quote }}
{{- end }}
