---
# Source: frontegg-enterprise/charts/admins/charts/unified-chart-staging/templates/web/web-pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: admins-v2-web
spec:
  maxUnavailable: 30%
  selector:
    matchLabels:
      app.frontegg.com/name: admins-v2-web
---
# Source: frontegg-enterprise/charts/admins/charts/unified-chart-staging/templates/rbac/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admins-v2
  labels:
    helm.sh/chart: unified-chart-4.0.99
    app.frontegg.io/version: "4.0.99"
    app.frontegg.io/managed-by: Helm
    app.frontegg.com/team: frontegg
    app.frontegg.com/appVersion: "master-latest"
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
---
# Source: frontegg-enterprise/charts/admins/charts/unified-chart-staging/templates/config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
    argocd.argoproj.io/sync-wave: "-100"
  name: admins-v2
  labels:
    helm.sh/chart: unified-chart-4.0.99
    app.frontegg.io/version: "4.0.99"
    app.frontegg.io/managed-by: Helm
    app.frontegg.com/team: frontegg
    app.frontegg.com/appVersion: "master-latest"
data:
  CLOUD_ENVIRONMENT: "production"
  FRONTEGG_CONFIG_FILE_PATH: "/etc/config/config.env"
  NODE_ENV: "production"
  name: "admins-v2"
---
# Source: frontegg-enterprise/templates/config-center.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-center
  labels:
    helm.sh/chart: frontegg-enterprise-0.0.1
    app.frontegg.com/name: frontegg-enterprise
    app.frontegg.com/instance: pook
    app.frontegg.io/version: "0.0.1"
    app.frontegg.io/managed-by: Helm
data:
  prehook-service-url: "http://frontegg-prehook-service"
  admins-service-url: "http://frontegg-admins-service"
  audits-service-url: "http://frontegg-audits-service"
  authentication-service-url: "http://frontegg-authentication-service"
  metadata-service-url: "http://frontegg-metadata-service"
  notification-service-url: "http://frontegg-notification-service"
  reports-engine-url: "http://frontegg-reporting-engine"
  reports-service-url: "http://frontegg-reporting-service"
  team-service-url: "http://frontegg-team-management-service"
  vendors-service-url: "http://frontegg-vendors-service"
  tenants-service-url: "http://frontegg-tenants-service"
  webpush-service-url: "http://frontegg-webpush-service"
  webhook-service-url: "http://frontegg-webhook-service"
  events-service-url: "http://frontegg-event-service"
  identity-service-url: "http://frontegg-identity-service"
  nlp-execution-assistant-url: "http://nlp-execution-assistant-v2-web"
  identity-p1-service-url: "http://frontegg-identity-service-hp"
  integrations-service-url: "http://frontegg-integrations-service"
  api-gateway-url: "https://dev-api.frontegg.com"
  api-gateway-internal-url: "http://api-gateway-v2-web"
  oauth-service-url: "http://frontegg-oauth-service"
  subscriptions-service-url: "http://frontegg-subscriptions-service"
  usage-tracking-service-url: "http://usage-tracking-service"
  env-duplicator-service-url: "http://frontegg-env-duplicator-service"
  policy-service-url: "http://frontegg-policy-service"
  dashboard-env-builder-url: "http://frontegg-dashboard-env-builder-service"
  frontegg-vendor-host: "EMPTY"
  cdn-url: ""
  backoffice-service-url: "http://frontegg-backoffice-service"
  pricing-views-url: "http://frontegg-pricing-views-service"
  email-service-url: "http://frontegg-email-service"
  directory-service-url: "http://frontegg-directory-service"
  logs-service-url: "http://frontegg-logs-service"
  logs-streaming-service-url: "http://frontegg-logs-streaming-service"
  entitlements-service-url: "http://frontegg-entitlements-service"
  security-engines-url: "http://frontegg-security-engines"
  applications-service-url: "http://frontegg-applications-service"
  signals-service-url: "http://frontegg-signals-service"
  security-center-service-url: "http://frontegg-security-center-service"
  custom-code-service-url: "http://frontegg-custom-code-service"
  entitlements-agent-url: "http://frontegg-entitlements-agent"
  auth-hub-service-url: "http://auth-hub-v2-web"
  anomaly-detection-url: "http://anomaly-detection-v2-web"
  idgw-backend-url: ""
  mcp-server-url: ""
  aws-region: ""
  policy-service-aws-region: ""
  policy-service-s3-opa-policy-bucket: ""
  entitlements-service-s3-opa-policy-bucket: ""
  custom-code-service-lambda-management-role-arn: ""
  custom-code-service-lambda-execution-role-arn: ""
  custom-code-service-lambda-execution-default-policies: ""
  custom-code-service-lambda-layers: ""
  custom-code-service-lambda-env-cx-domain: ""
  env-id: ""
  portal-url: ""
  portal-v1-url: ""
  cors-origin: ""
  custom-domain-cloudflare-ssl-endpoint: ""
  tracing-collector-endpoint: http://logzio-otel-traces.observability.svc.cluster.local:14268/api/traces
  idgw-application-id: ""
  splitio-proxy-endpoint: http://split-proxy-v2-web.feature-management.svc.cluster.local
  audits-topic-name: "audits-v1"
  audits-db-type: "mysql"
  audits-db-name: "frontegg_audits"
  metadata-service-fetch-pubsub-strategy: "true"
  metadata-service-topic-name: "METADATA_UPDATED"
  audits-service-redis-db-index: "2"
  audits-kafka-retry-count: "3"
  authentication-cookie-domain: ""
  authentication-secured-cookie: ""
  api-gateway-enable-redis-store: ""
  api-gateway-usage-reporting-enabled: ""
  api-gateway-metrics-enabled: ""
  api-gateway-redis-db-index: "9"
  enable-multi-hosts: ""
  api-gateway-ignore-hosts: ""
  api-gateway-redirect-enabled: "false"
  api-gateway-redirect-url: ""
  backoffice-redis-db-index: "12"
  entitlements-redis-db-index: "12"
  entitlements-vendor-snapshot-job-delay-ms: "10000"
  entitlements-vendor-snapshot-job-attempts: "3"
  entitlements-service-legacy-vendors-plan-ids: ""
  connectors-worker-service-redis-db-index: "5"
  mixpanel-id: ""
  dashboard-hubspot-enabled: ""
  dashboard-devrev-enabled: "true"
  devrev-api-url: "https://api.devrev.ai"
  dashboard-domain-suffix: ""
  dashboard-cdn-url: ""
  cdn-bucket: ""
  backoffice-viewer-role-id: ""
  backoffice-editor-role-id: ""
  frontegg-ui-events-url: "https://ui-events.frontegg.com"
  env-duplicator-mysql-db-name: "frontegg_env_duplicator"
  env-duplicator-configuration-copy-result-topic-name: "configuration-copy-result-v1"
  env-duplicator-configuration-copy-topic-name: "configuration-copy-v1"
  events-service-redis-db-index: "7"
  identity-service-db-name: "frontegg_identity"
  identity-service-audit-triggered-topic-name: "AUDIT_TRIGGERED"
  identity-service-max-concurrent-sessions: "100"
  metadata-service-db-connection-timeout-ms: "30000"
  metadata-service-db-connection-retry-attempts: "3"
  metadata-service-db-connection-retry-delay: "1000"
  metadata-service-ip-stack-url: ""
  metadata-service-redis-db-index: "0"
  events-pubsub-topic: "events"
  oauth-service-db-name: "frontegg_oauth"
  oauth-service-redis-db-index: "10"
  team-management-service-db-name: "frontegg_team_management"
  team-management-service-vault-url: "" ### check this
  team-management-service-redis-db-index: "1"
  team-management-service-authorization-topic-name: "authorization-v1"
  tenants-usage-reporting-topic-name: "usage-reporting-v1"
  tenants-redis-db-index: "8"
  tenants-service-mysql-db-name: "frontegg_tenants"
  tenant-assets-s3-url: "https://-tenants-assets.s3..amazonaws.com"
  tenant-assets-s3-bucket: ""
  tenant-assets-s3-endpoint: ""
  tenant-assets-s3-aws-endpoint: ""
  vendors-mysql-db-name: "frontegg_vendors"
  vendors-asset-blob-storage-container-name: "public-vendor-assets"
  vendors-service-vendors-domain: "dev.frontegg.com"
  custom-domain-cluster-ingress-class: "nginx"
  custom-domain-cluster-issuer-name: "letsencrypt"
  custom-domain-cluster-default-port: "443"
  custom-domain-cluste-namespace: "custom-domains"
  custom-domain-ssl-endpoint: ""
  custom-domain-cloudflare-transform-rule-set-id: "xxxx"
  custom-domain-cloudflare-origin-rule-set-id: "xxxx"
  vendors-service-kafka-vendors-topic: "vendors-v1"
  webhook-service-mongodb-connection-retry-attempts: "3"
  webhook-service-mongodb-connection-retry-delay: "1000"
  webhook-mysql-db-name: "frontegg_webhooks"
  webhook-proxy-enabled: "true"
  frontegg-proxy-host: "frontegg-forward-proxy"
  frontegg-proxy-port: "8080"
  frontegg-proxy-protocol: "http"

  # TODO: add secret '$secret.frontegg.forwardProxy.auth.password'
---
# Source: frontegg-enterprise/charts/admins/charts/unified-chart-staging/templates/web/web-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: admins-v2-web
  labels:
    app.frontegg.com/team: frontegg
    app.frontegg.com/appVersion: "master-latest"
    app.frontegg.com/name: admins-v2-web
    monitoring-metrics: enabled
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3004
      protocol: TCP
      name: http
  selector:
    app.frontegg.com/name: admins-v2-web
---
# Source: frontegg-enterprise/charts/admins/charts/unified-chart-staging/templates/web/web-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admins-v2-web
  labels:
    app.frontegg.com/team: frontegg
    app.frontegg.com/appVersion: "master-latest"
    app.frontegg.com/name: admins-v2-web
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.frontegg.com/name: admins-v2-web
  template:
    metadata:
      labels:
        app.frontegg.com/team: frontegg
        app.frontegg.com/appVersion: "master-latest"
        app.frontegg.com/name: admins-v2-web
      annotations:
        checksum/secret: c0e20220fff95520aeba60c40779d532afa1b44a3db29cb127fab75a69db8da7
        
    spec:
      serviceAccountName: admins-v2
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: secret-volume
          secret:
            secretName: admins-v2
      containers:
        - name: admins
          image: "527305576865.dkr.ecr.us-east-1.amazonaws.com/docker-hub/frontegg/admins-service:master-latest"
          imagePullPolicy: Always
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/config/config.env
              subPath: config
          ports:
            - containerPort: 3004
              name: http
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          env:            
            - name: FRONTEGG_IDENTITY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: config-center
                  key: identity-service-url
            - name: FRONTEGG_TENANTS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: config-center
                  key: tenants-service-url
            - name: FRONTEGG_VENDORS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: config-center
                  key: vendors-service-url
            - name: PORTAL_URL
              valueFrom:
                configMapKeyRef:
                  name: config-center
                  key: portal-url
          envFrom:
            - configMapRef:
                name: admins-v2
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
          command:
            - "/bin/bash"
          args:
            - "entrypoint.sh"
---
# Source: frontegg-enterprise/charts/admins/charts/unified-chart-staging/templates/web/web-hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: admins-v2-web
  labels:
    app.frontegg.com/team: frontegg
    app.frontegg.com/appVersion: "master-latest"
    app.frontegg.com/name: admins-v2-web
  annotations:
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: admins-v2-web
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
---
# Source: frontegg-enterprise/charts/admins/charts/unified-chart-staging/templates/secrets/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: admins-v2
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
    argocd.argoproj.io/sync-wave: "-100"
  labels:
    helm.sh/chart: unified-chart-4.0.99
    app.frontegg.io/version: "4.0.99"
    app.frontegg.io/managed-by: Helm
    app.frontegg.com/team: frontegg
    app.frontegg.com/appVersion: "master-latest"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: external-secret-store
    kind: ClusterSecretStore
  target:
    name: admins-v2
    template:
      engineVersion: v2
      data:
        config: |
          {{- $secret := .contents | fromYaml }}
          FRONTEGG_EVENT_SERVICE_API_KEY={{ $secret.frontegg.apiKeys.eventsServiceApiKey | toYaml }}
          FRONTEGG_ADMINS_SERVICE_API_KEY={{ $secret.frontegg.apiKeys.adminsServiceApiKey | toYaml }}
          FRONTEGG_VENDORS_SERVICE_API_KEY={{ $secret.frontegg.apiKeys.vendorsServiceApiKey | toYaml }}
          FRONTEGG_IDENTITY_SERVICE_API_KEY={{ $secret.frontegg.apiKeys.identityServiceApiKey | toYaml }}
          FRONTEGG_CLIENT_ID={{ $secret.frontegg.xxx.fronteggClientId | toYaml }}
          FRONTEGG_KAFKA_BROKER_LIST={{ $secret.databases.kafka.brokerList | toYaml }}
          FRONTEGG_KAFKA_SASL_PASSWORD={{ $secret.databases.kafka.saslPassword | toYaml }}
          FRONTEGG_KAFKA_SASL_USERNAME={{ $secret.databases.kafka.saslUserName | toYaml }}
          FRONTEGG_SPLIT_IO_KEY={{ $secret.externalServices.split.sdkKey | toYaml }}
          FRONTEGG_TENANTS_SERVICE_API_KEY={{ $secret.frontegg.apiKeys.tenantsServiceApiKey | toYaml }}
          
  data:
    - secretKey: contents
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: prod-main-secret20250407120514343900000001
