

configCenter:
  externalServices:
    secrets:
      url: ""
    iot:
      topic: ""
    aws:
      region: ""
      componentsCollectionIdentifier: ""

  frontegg:
    general:
      analytics:
        segmentAnalyticsEnabled: "false"
        useFirehoseAnalytics: "true"
      portalUrl: ""
      corsOrigin: ""
      portalV1Url: ""
      customDomainCloudflareEndpoint: ""
      tracingCollectorEndpoint: "http://logzio-otel-traces.observability.svc.cluster.local:14268/api/traces"
      idgwApplicationId: ""
      splitioProxyEndpoint: "http://split-proxy-v2-web.feature-management.svc.cluster.local"
    applications:
      audits:
        auditsTopicName: "audits-v1"
        auditsDbType: "mysql"
        auditsDbName: "frontegg_audits"
        metadataServiceFetchPubsubStrategy: "true"
        metadataServiceTopicName: "METADATA_UPDATED"
        auditsServiceRedisDbIndex: "2"
        auditsKafkaRetryCount: "3"
      authentication:
        authenticationCookieDomain: ""
        authenticationSecuredCookie: ""
      apiGateway:
        apiGatewayUsageReportingEnabled: ""
        apiGatewayMetricsEnabled: ""
        apiGatewayRedisDbIndex: "9"
        enableMultiHosts: ""
        apiGatewayEnableRateLimiters: ""
        apiGatewayEnableRedisStore: ""
        apiGatewayIgnoredHosts:
        redirectEnabled: "false"
        redirectUrl: ""
      connectorsWorker:
        connectorsWorkerServiceRedisDbIndex: "5"
      dashboard:
        mixpanelId: ""
        dashboardHubspotEnabled: ""
        dashboardDevrevEnabled: "true"
        devrevApiUrl: "https://api.devrev.ai"
        dashboardDomainSuffix: ""
        cdnUrl: ""
        cdnBucket: ""
        backofficeViewerRoleId: ""
        backofficeEditorRoleId: ""
        fronteggUiEventsUrl: "https://ui-events.frontegg.com"
      events:
        eventsServiceRedisDbIndex: "7"
      identity:
        identityServiceDbName: "frontegg_identity"
        identityServiceAuditTriggeredTopicName: "AUDIT_TRIGGERED"
        identityServiceMaxConcurrentSessions: "100"
      metadata:
        metadataServiceDbConnectionTimeoutMs: "30000"
        metadataServiceDbConnectionRetryAttempts: "3"
        metadataServiceDbConnectionRetryDelay: "1000"
        metadataServiceRedisDbIndex: "0"
      notifications:
        eventsPubsubTopic: "events"
      reportingEngine:
        assetBlobStorageContainerName: "vendor-assets"
        reportingEngineApproversNotificationEmailTemplateId:
        iotRedisDbIndex: "4"
        iotRedisRecordTtlSeconds: "600"
        iotRedisMaxPollTimeoutMs: "60000"
        iotRedisPollIntervalMs: "1000"
        bucketUrl: ""
      reportsScheduler:
        reportingServiceFetchPubsubStrategy: "true"
        reportingServiceTopicName: "reporting-changes"
      subscription:
        stripeRegion: "eu"
        defaultStripeRegion: "eu"
      teamManagement:
        teamManagementServiceDbName: "frontegg_team_management"
        teamManagementServiceRedisDbIndex: "1"
        teamManagementServiceAuthorizationTopicName: "authorization-v1"
      tenants:
        tenantsUsageReportingTopicName: "usage-reporting-v1"
        tenantsRedisDbIndex: "8"
        tenantsServiceMysqlDbName: "frontegg_tenants"
        tenantAssetsS3Bucket: ""
        tenantAssetsS3Url: "https://{{ $.Values.configCenter.externalServices.aws.componentsCollectionIdentifier }}-tenants-assets.s3.{{ $.Values.configCenter.externalServices.aws.region }}.amazonaws.com"
        s3:
          tenantsServiceAwsEndpoint: ""
          tenantsServiceTenantAssetsS3Endpoint: ""
      customCode:
        lambda:
          management:
            roleArn: ""
          execution:
            roleArn: ""
            defaultPolicies: ""
          environment:
            variables:
              cxDomain: ""
          layers: ""
      vendors:
        vendorsServiceMysqlDbName: "frontegg_vendors"
        vendorsAssetBlobStorageContainerName: "public-vendor-assets"
        vendorsServiceVendorsDomain: "dev.frontegg.com"
        customDomainClusterIngressClass: "nginx"
        customDomainClusterIssuerName: "letsencrypt"
        customDomainClusterDefaultPort: "443"
        customDomainClusteNamespace: "custom-domains"
        customDomainSslEndpoint: ""
        customDomainCloudflareTransformRuleSetId: "xxxx"
        customDomainCloudflareOriginRuleSetId: "xxxx"
        kafkaVendorsTopic: "vendors-v1"
      webhooks:
        webhookServiceMongodbConnectionRetryAttempts: "3"
        webhookServiceMongodbConnectionRetryDelay: "1000"
        webhookMysqlDbName: "frontegg_webhooks"
        proxyEnabled: "true"
      webpush:
        webpushMongodbConnectionRetryAttempts: "3"
        webpushMongodbConnectionRetryDelay: "1000"
      sidekick:
        sidekickAllowedOrigin: "*"
        sidekickTenantId: ""
      dataIngest:
        dataIngestDbSchema: "frontegg_ingest"
        dataIngestKafkaTopic: "usage-reporting-v1"
        dataIngestKafkaVendorsTopic: "vendors-v1"
      pqlProcess:
        pqlProcessHubspotEnableCompaniesSync: ""
        pqlProcessHubspotEnableReporting: ""
      oauth:
        oauthServiceDbName: "frontegg_oauth"
        oauthServiceRedisDbIndex: "10"
      policy:
        opaPolicyBucket: ""
        configCopyResultTopicName: "configuration-copy-result-v1"
        configCopyTopicName: "configuration-copy-v1"
      envDuplicator:
        configCopyResultTopicName: "configuration-copy-result-v1"
        configCopyTopicName: "configuration-copy-v1"
        dbName: "frontegg_env_duplicator"
      backoffice:
        redis:
          redisDbIndex: "12"
      entitlements:
        redisDBIndex: "12"
        vendorSnapshotJobDelayMS: "10000"
        vendorSnapshotJobAttempts: "3"
        opaPolicyBucket: ""
      forwardProxy:
        isAuthRequired: "false"
        host: "frontegg-forward-proxy"
        port: "8080"
        protocol: "http"

    services:
      prehookServiceUrl: "http://frontegg-prehook-service"
      adminsServiceUrl: "http://frontegg-admins-service"
      auditsServiceUrl: "http://frontegg-audits-service"
      authenticationServiceUrl: "http://frontegg-authentication-service"
      metadataServiceUrl: "http://frontegg-metadata-service"
      notificationServiceUrl: "http://frontegg-notification-service"
      reportsEngineUrl: "http://frontegg-reporting-engine"
      reportsServiceUrl: "http://frontegg-reporting-service"
      teamServiceUrl: "http://frontegg-team-management-service"
      vendorsServiceUrl: "http://frontegg-vendors-service"
      tenantsServiceUrl: "http://frontegg-tenants-service"
      webpushServiceUrl: "http://frontegg-webpush-service"
      webhookServiceUrl: "http://frontegg-webhook-service"
      eventsServiceUrl: "http://frontegg-event-service"
      identityServiceUrl: "http://frontegg-identity-service"
      identityP1ServiceUrl: "http://frontegg-identity-service-hp"
      integrationsServiceUrl: "http://frontegg-integrations-service"
      apiGatewayUrl: "https://dev-api.frontegg.com"
      apiGatewayInternalUrl: "http://api-gateway-v2-web"
      oauthServiceUrl: "http://frontegg-oauth-service"
      subscriptionsServiceUrl: "http://frontegg-subscriptions-service"
      policyServiceUrl: "http://frontegg-policy-service"
      usageTrackingUrl: "http://usage-tracking-service"
      envDuplicatorUrl: "http://frontegg-env-duplicator-service"
      dashboardEnvBuilderUrl: "http://frontegg-dashboard-env-builder-service"
      backofficeUrl: "http://frontegg-backoffice-service"
      pricingViewsUrl: "http://frontegg-pricing-views-service"
      emailServiceUrl: "http://frontegg-email-service"
      directoryServiceUrl: "http://frontegg-directory-service"
      logsServiceUrl: "http://frontegg-logs-service"
      logsStreamingServiceUrl: "http://frontegg-logs-streaming-service"
      entitlementsServiceUrl: "http://frontegg-entitlements-service"
      securityEnginesUrl: "http://frontegg-security-engines"
      securityCenterServiceUrl: "http://frontegg-security-center-service"
      signalsServiceUrl: "http://frontegg-signals-service"
      applicationsServiceUrl: "http://frontegg-applications-service"
      customCodeServiceUrl: "http://frontegg-custom-code-service"
      entitlementsAgentUrl: "http://frontegg-entitlements-agent"
      authHubServiceUrl: "http://auth-hub-v2-web"
      nlpExecutionAssistantUrl: "http://nlp-execution-assistant-v2-web"
      anomalyDetectionUrl: "http://anomaly-detection-v2-web"
      fronteggVendorHost: "EMPTY"