{{- $top := . -}}
{{- $values := .Values -}}
{{- if .Values.worker.enabled }}
{{- if .Values.argoRollouts.progressiveDelivery.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "worker.name" $top }}-route
spec:
  parentRefs:
    {{- range $values.worker.service.ports }}
    - group: "core"
      name: {{ include "worker.name" $top  }}
      kind: Service
      port: {{ required ".Values.worker.service.ports[*].port number is required" .port }}
    {{- end }}
  rules:
    - backendRefs:
    {{- range $values.worker.service.ports }}
      - name: {{ include "worker.name" $top  }}-canary
        group: "core"
        port: {{ required ".Values.worker.service.ports[*].port number is required" .port }}
        kind: Service
      - name: {{ include "worker.name" $top  }}
        group: "core"
        port: {{ required ".Values.worker.service.ports[*].port number is required" .port }}
        kind: Service
    {{- end }}
{{- end }}
{{- end }}

