{{- $top := . -}}
{{- $values := .Values -}}
{{- if .Values.worker.enabled }}
{{- if .Values.argoRollouts.progressiveDelivery.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "worker.name" . }}
spec:
  args:
    - name: service-name
      value: {{ include "githubrepo.name" . }}
  metrics:
    - name: succesful-black-box-test
      successCondition: "result.status_code == 200"
      {{- with .Values.argoRollouts.progressiveDelivery }}
      failureLimit: {{ .blackBox.failureLimit | default "1" }} 
      count: {{ .blackBox.count | default "1" }}
      consecutiveErrorLimit: {{ .blackBox.consecutiveErrorLimit | default "0" }}
      provider:
        web:
          method:  {{ .blackBox.method | default "POST" }}
          url: {{ .blackBox.url | default "http://nexus-v2-web.frontegg.svc.cluster.local/blackbox" }}
          timeoutSeconds: {{ .blackBox.timeout | default "1200" }} 
          headers:
            {{- range  $header := .blackBox.headers }}
            - key: {{ $header.key }} 
              value: {{ $header.value }}
            {{- end }}
          jsonBody:
            service-name: {{ include "githubrepo.name" $top }}
            version: {{ include "appVersion" $top }}
      {{- end }}
{{- end }}  
{{- end }}  
