{{- $values := .Values -}}
{{- if $values.worker.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "worker.name" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
    {{- include "fail.if.empty" $values.worker.service }}
    {{- with $values.worker.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ $values.worker.service.type }}
  ports:
    {{- include "validate.ports" $values.worker.service }}
    {{- range $values.worker.service.ports }}
    - port: {{ required ".Values.worker.service.ports[*].port number is required" .port }}
      targetPort: {{ required "need to know if someone listening: .Values.worker.service.ports[*].targetPort is required" .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name | default "http" }}
    {{- end }}
  selector:
    {{- include "worker.selector.labels" . | nindent 4 }}
{{- end }}