kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "audits-service.fullname" . }}-configmap
  labels:
  {{- include "api-gateway.labels" . | nindent 4 }}
data:
  FRONTEGG_HYBRID_MODE: "true"
  FRONTEGG_PORT: 3002
  FRONTEGG_SPLIT_IO_KEY: ''
