kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "audits-service.fullname" . }}-configmap
  labels:
  {{- include "audits-service.labels" . | nindent 4 }}
data:
  NODE_ENV: production
  FRONTEGG_HYBRID_MODE: "true"
  FRONTEGG_PORT: "3002"
  FRONTEGG_SPLIT_IO_KEY: ''
  FRONTEGG_AUDITS_SERVICE_API_KEY: "frontegg-api-key"
