apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "audits-service.fullname" . }}-deployment
  labels:
  {{- include "audits-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
  {{- include "audits-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.frontegg.com/appVersion: {{ .Values.appVersion | quote}}
      {{- include "audits-service.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ (print .Values.configmap) | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.externalSecret }}
      {{- if .Values.externalSecret.enabled }}
      volumes:
        - name: vol-secret
          secret:
            secretName: {{ include "audits-service.fullname" . }}-external-secret
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.appVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.externalSecret }}
          {{- if .Values.externalSecret.enabled }}
          volumeMounts:
            - name: vol-secret
              mountPath: /etc/config/config.env
              subPath: config
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }} # change this to 80 in the future
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
          {{- range $config_name, $values := .Values.configuration.map }}
          {{- range $key, $value :=  $values}}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $config_name }}
                  key: {{ $value }}
          {{- end }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "audits-service.fullname" . }}-configmap
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
