apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audits-service.fullname" . }}-secret
  labels:
  {{- include "api-gateway.labels" . | nindent 4 }}
data:
  {{- with .Values.frontegg }}
  FRONTEGG_CLIENT_ID: {{ required "A valid .Values.frontegg.clientId entry required!" .clientId | b64enc | quote }}
  FRONTEGG_API_KEY: {{ required "A valid .Values.frontegg.apiKey entry required!" .apiKey | b64enc | quote }}
  {{- with .sync }}
  FRONTEGG_METADATA_SERVICE_URL: {{ .metadataServiceUrl | b64enc | quote }}
  FRONTEGG_METADATA_SERVICE_FETCH_PUBSUB_STRATEGY: {{ .metadataServiceFetchPubsubStrategy | b64enc | quote }}
  FRONTEGG_AUDITS_SERVICE_HYBRID_AUTH_RETRY_DELAY_MS: {{ .authenticationRetryDelay | b64enc | quote }}
  FRONTEGG_AUDITS_SERVICE_HYBRID_SHUTDOWN_ON_INITIAL_AUTH_FAILURE: {{ .shutdownOnAuthenticationFailure | b64enc | quote }}
  FRONTEGG_AUTHENTICATION_URL: {{ .authenticationUrl | b64enc | quote }}
  {{- end }}
  {{- end }}

  {{- with .Values.kafka }}
  FRONTEGG_KAFKA_BROKER_LIST: {{ required "A valid .Values.kafka.brokerList entry required!" .brokerList | b64enc | quote }}
  FRONTEGG_KAFKA_SASL_PASSWORD: {{ .sslPassword | b64enc | quote }}
  FRONTEGG_AUDITS_TOPIC_NAME: {{ .topicName | b64enc | quote }}
  {{- end }}
  {{- with .Values.mysql }}
  FRONTEGG_AUDITS_DB_HOST: {{ required "A valid .Values.mysql.host entry required!" .host | b64enc | quote }}
  FRONTEGG_AUDITS_DB_USERNAME: {{ required "A valid .Values.mysql.userName entry required!" .userName | b64enc | quote }}
  FRONTEGG_AUDITS_DB_PASSWORD: {{ .password | b64enc | quote }}
  FRONTEGG_AUDITS_DB_NAME: {{ required "A valid .Values.mysql.dbName entry required!" .dbName | b64enc | quote }}
  FRONTEGG_AUDITS_DB_USE_SSL: {{ required "A valid .Values.mysql.useSsl entry required!" .useSsl | b64enc | quote }}
  {{- end }}

