apiVersion: v2
name: frontegg-enterprise
description: Frontegg Enterprise Helm Chart # FILL IN BY MARKETING
type: application

version: 0.0.1
appVersion: 2025.04.01

maintainers:
  - name: "Frontegg"
    email: "support@frontegg.com"

dependencies:
  - name: unified-chart-staging
    version: &chartVersion 4.0.*
    repository: https://frontegg.github.io/helm-charts
    alias: admins

  - name: unified-chart-staging
    version: *chartVersion
    repository: https://frontegg.github.io/helm-charts
    alias: pook