{{- $top := . -}}
{{- $values := $top.Values -}}
{{- if and $values.e10sEngineSync.enabled $values.e10sEngineSync.secret.enabled (not $values.e10sEngineSync.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "e10sEngineSync.secret.name" $top }}
  labels:
    {{- include "e10sEngineSync.labels" $top | nindent 4 }}
type: Opaque
stringData:
  FRONTEGG_CLIENT_ID: {{ required ".Values.e10sEngineSync.frontegg.clientId is required" $values.e10sEngineSync.frontegg.clientId | quote }}
  FRONTEGG_CLIENT_SECRET: {{ required ".Values.e10sEngineSync.frontegg.clientSecret is required" $values.e10sEngineSync.frontegg.clientSecret | quote }}
  SPICEDB_GRPC_PRESHARED_KEY: {{ required ".Values.e10sEngineSync.spicedb.presharedKey is required" $values.e10sEngineSync.spicedb.presharedKey | quote }}
  {{- with $values.e10sEngineSync.secret.additionalData }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}

