---
kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    {{- with .Values.configmap.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  name: {{ include "fuc.name" . }}-configmap
  labels:
    {{- include "fuc.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configmap.data | nindent 2 }}
  {{- tpl .Values.configmap.tplData $ | nindent 2 }}
