{{- if .Values.configmap.data }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    {{- with .Values.configmap.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  name: {{ include "name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  {{- range $key,$value := .Values.configmap.data }}
  {{ tpl $key $ }}: {{ tpl $value $ | quote }}
  {{- end }}
{{- end }}