---
kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    {{- with .Values.configmap.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  name: {{ include "configmap.checksum" $ | trunc 63 }}
  labels:
    {{- include "unified.labels" . | nindent 4 }}
data:
  {{- range $key,$value := .Values.configmap.data }}
  {{ tpl $key $ }}: {{ tpl $value $ | quote }}
  {{- end }}
