{{- if .Values.serviceAccount.enabled -}}
{{- if not .Values.serviceAccount.nameOverride }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}