{{- if .Values.albIngress.enabled -}}
{{- $name := include "unified.name" . -}}
{{- $svcPort := .Values.service.port -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ required ".Values.name is required" .Values.name }}-alb
  labels:
    {{- include "unified.labels" . | nindent 4 }}
  {{- with .Values.albIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.albIngress.ingressClassName }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  rules:
    - host: {{ include "unified.hostname" . | quote }}
      http:
        paths:
        - path: /
          backend:
            service:
              name: frontegg-{{ include "unified.name" . }}
              port:
                number: {{ $svcPort }}
          pathType: ImplementationSpecific
{{- end }}