{{- $top := . }}
{{- $values := .Values }}
{{- range $ingname, $ingress := .Values.ingresses }}
{{- if $ingress.enabled }}
{{- $name := include "name" $top }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ required ".Values.name is required" $values.name }}-{{ $ingname }}
  labels:
    {{- include "labels" $top | nindent 4 }}
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $ingress.ingressClassName }}
  ingressClassName: {{ . | quote }}
  {{- end }}
{{- with $ingress.tls }}
{{- if .enabled}}
  tls:
    - hosts:
        - {{ required "Need a proper hostname, u idiot!" $ingress.hostnameOverride | quote }}
      secretName: {{ .secretName }}
{{- end }}
{{- end }}
  rules:
    - host: {{ $ingress.hostnameOverride | quote }}
      http:
        paths:
        - path: /
          backend:
            service:
              name: {{ tpl ($ingress.service.name | default "frontegg-{{ include \"name\" $ }}") $top }}
              port:
                number: {{ $ingress.service.port | default 80 }}
          pathType: ImplementationSpecific
{{- end }}
{{- end }}