{{- if .Values.web.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unified.web.name" . }}
  labels:
    {{- toYaml .Values.service.labels | nindent 4 }}
    {{- include "unified.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ required ".Values.service.targetPort is required" .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name | default "http" }}
  selector:
    {{- include "unified.selectorLabels" . | nindent 4 }}
{{- end }}