---
apiVersion: v1
kind: Service
metadata:
  name: frontegg-{{ include "fuc.name" . }}-service
  labels:
    monitoring-metrics: enabled
    {{- include "fuc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "fuc.selectorLabels" . | nindent 4 }}

{{- $serviceName := (include "fuc.name" .) }}
{{- if has $serviceName .Values.doubleSVC }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontegg-{{ include "fuc.name" . }}
  labels:
    monitoring-metrics: enabled
    {{- include "fuc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "fuc.selectorLabels" . | nindent 4 }}
{{- end }}