---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fuc.web.svc.name" . }}
  labels:
    monitoring-metrics: enabled
    {{- include "fuc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "fuc.selectorLabels" . | nindent 4 }}