{{- if .Values.web.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.name" . }}
  labels:
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ required "need to know if someone listening: .Values.service.targetPort is required" .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name | default "http" }}
  selector:
    {{- include "selector.labels" . | nindent 4 }}
{{- end }}