{{- if .Values.web.enabled -}}
{{- if .Values.argoRollouts }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "unified.web.name" . }}
spec:
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "unified.web.name" . }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "unified.selectorLabels" . | nindent 6 }}
  strategy:
    blueGreen:
      activeService: {{ include "unified.web.name" . }}
      autoPromotionEnabled: true
{{- end }}
{{- end }}