{{- if .Values.initDbJob.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "frontegg-enterprise.fullname" . }}-initdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontegg-enterprise.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-50"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "frontegg-enterprise.selectorLabels" . | nindent 8 }}
        job-name: {{ include "frontegg-enterprise.fullname" . }}-initdb
    spec:
      restartPolicy: Never
      containers:
      - name: mysql-client
        image: "{{ .Values.initDbJob.image.repository }}:{{ .Values.initDbJob.image.tag }}"
        imagePullPolicy: {{ .Values.initDbJob.image.pullPolicy }}
        env:
        - name: MYSQL_HOST
          value: "prod-mysql8-0-35.c1hrwrvemzzh.us-east-1.rds.amazonaws.com"
        - name: MYSQL_USER
          value: "rdsmaster_IhsLkE"
        - name: MYSQL_PASSWORD
          value: "CGXiW7u4KJNKBRK2fjnja5QgnDbzOk57"
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for DB host $MYSQL_HOST..."
          # Simple wait loop (adjust timeout/checks as needed)
          timeout=60
          while ! mysqladmin ping -h"$MYSQL_HOST" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" --silent; do
            timeout=$(($timeout - 1))
            if [ $timeout -eq 0 ]; then
              echo "Timeout waiting for DB."
              exit 1
            fi
            sleep 1
          done
          echo "DB host ready. Executing script..."
          mysql -h"$MYSQL_HOST" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" < /scripts/db.sql
          echo "Script execution finished."
        volumeMounts:
        - name: initdb-scripts
          mountPath: /scripts
      volumes:
      - name: initdb-scripts
        configMap:
          name: {{ include "frontegg-enterprise.fullname" . }}-initdb-scripts
{{- end }} 