apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "frontegg-enterprise.fullname" . }}-encrypt
  labels:
    app.kubernetes.io/name: {{ include "frontegg-enterprise.name" . }}
    helm.sh/chart: {{ include "frontegg-enterprise.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: task-master-cli
          image: {{ index .Values "task-master" "image" "prefix" }}{{ index .Values "task-master" "image" "repository" }}:{{ index .Values "task-master" "appVersion" }}
          env:
            - name: EMAIL
              value: {{ .Values.taskMasterEncryptJob.email | quote }}
            - name: PASSWORD
              value: {{ .Values.taskMasterEncryptJob.password | quote }}
            - name: FRONTEGG_CONFIG_DIRECTORY
              value: "/usr/src/app/config"
          command:
            - /bin/sh
            - -c
            - |
              # Read values from the mounted secret file
              IDENTITY_CRYPTO_KEY=$(yq eval '.identityCryptoKey' /usr/src/app/config/config.yaml)
              PUBLIC_KEY_BASE64=$(yq eval '.authPublicKey' /usr/src/app/config/config.yaml)
              TEMP_PRIVATE_KEY=$(yq eval '.fronteggPrivateKey' /usr/src/app/config/config.yaml)
              
              # Debug: Print values (first 50 chars for security)
              echo "Identity Crypto Key: ${IDENTITY_CRYPTO_KEY:0:50}..."
              echo "Public Key (first 50 chars): ${PUBLIC_KEY_BASE64:0:50}..."
              echo "Private Key (first 50 chars): ${TEMP_PRIVATE_KEY:0:50}..."
              
              # Encrypt the private key using the identity crypto key
              echo "Encrypting private key..."
              ENCRYPTED_KEY=$(task-master-cli encrypt "$TEMP_PRIVATE_KEY")
              echo "Encrypted key (first 50 chars): ${ENCRYPTED_KEY:0:50}..."
              
              # Run the create environment command
              echo "Creating Frontegg environment..."
              task-master-cli run create-frontegg-env -d "{
                \"userData\": {
                  \"email\": \"$EMAIL\",
                  \"password\": \"$PASSWORD\"
                },
                \"vendorKeys\": {
                  \"private\": \"$ENCRYPTED_KEY\",
                  \"publicEncoded\": \"$PUBLIC_KEY_BASE64\"
                }
              }"
          volumeMounts:
            - name: config
              mountPath: /usr/src/app/config/config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: task-master-v2