{{- $top := . -}}
{{- $values := .Values -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "frontegg-enterprise.fullname" . }}-encrypt
  annotations:
    "helm.sh/hook": post-install,post-upgrade

spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: task-master-cli
          image: {{ index .Values "task-master" "image" "prefix" }}{{ index .Values "task-master" "image" "repository" }}:{{ index .Values "task-master" "appVersion" }}
          env:
            - name: EMAIL
              value: {{ .Values.taskMasterEncryptJob.email | quote }}
            - name: PASSWORD
              value: {{ .Values.taskMasterEncryptJob.password | quote }}
            - name: SENDER_EMAIL
              value: {{ .Values.taskMasterEncryptJob.senderEmail | quote }}
            - name: FRONTEGG_CONFIG_DIRECTORY
              value: "/etc/config"
            {{- include "container.env" .Values.web | indent 12 -}}
            {{- range $config_name, $values := (index .Values "task-master").configuration.map }}
            {{- range $key, $value :=  $values}}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $config_name }}
                  key: {{ $value }}
            {{- end }}
            {{- end }}
          {{- if (index .Values "task-master").configmap.data }}
          envFrom:
            - configMapRef:
                name: task-master-v2
            {{- with (index .Values "task-master").web.additionalEnvFrom }}
            {{- tpl . $top | nindent 12 }}
            {{- end }}
          {{- end }}
          command:
            - /bin/sh
            - -c
            - |
              set -e
              task-master-cli create-frontegg-env

          volumeMounts:
            - mountPath: /etc/config/config.yaml
              subPath: config
              name: secret-volume
      volumes:
        - name: secret-volume
          secret:
            secretName: task-master-v2
