{{- if not .Values.proxysql.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxysql.fullname" . }}
data:
  proxysql.cnf: |
    {{ include "proxysql.cnf" . | b64enc | nindent 4 }}
{{- end }}
