api-gateway:
  name: api-gateway
  team: frontegg
  envID: "prod-main-secret20250407120514343900000001"
  image:
    repository: frontegg/api-gateway
    prefix: 527305576865.dkr.ecr.us-east-1.amazonaws.com/docker-hub/
  appVersion: 84c8fe4
  argoRollouts:
    enabled: false
  defaults:
    migration:
      annotations:
        "helm.sh/hook": pre-install, pre-upgrade
        "helm.sh/hook-weight": "-5"
        "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    configmap:
      annotations:
        "helm.sh/hook": pre-install, pre-upgrade
        "helm.sh/hook-weight": "-100"
        "helm.sh/hook-delete-policy": "before-hook-creation"
    secret:
      annotations:
        "helm.sh/hook": pre-install, pre-upgrade
        "helm.sh/hook-weight": "-100"
        "helm.sh/hook-delete-policy": "before-hook-creation"
    sereviceAccount:
      annotations:
        "helm.sh/hook": pre-install, pre-upgrade
        "helm.sh/hook-weight": "-100"

  web:
    enabled: true
    command: ["node"]
    args: ["--max-http-header-size=16384", "dist/api-gateway/main"]
    terminationGracePeriodSeconds: 60
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        memory: 2Gi
    service:
      ports:
        - port: 80
          targetPort: 9090
          protocol: TCP
          name: http
    ports:
      - name: http
        containerPort: 9090
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 4
      targetCPUUtilizationPercentage: 50
      targetMemoryUtilizationPercentage: 50
    readinessProbe:
      failureThreshold: 1
      httpGet:
        path: /healthcheck
        port: http
      initialDelaySeconds: 20
      periodSeconds: 5
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthcheck
        port: http
      initialDelaySeconds: 30
      periodSeconds: 60
    startupProbe:
      httpGet:
        path: /healthcheck
        port: http
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 5

  worker:
    enabled: true
    command: ["node"]
    args: ["--max-http-header-size=16384", "dist/worker/main"]
    labels:
      scrape-for-metrics: enabled
    service:
      ports:
        - port: 80
          targetPort: 9090
          protocol: TCP
          name: http
    ports:
      - name: http
        containerPort: 9090
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 50
      targetMemoryUtilizationPercentage: 75
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
    readinessProbe: {}
    livenessProbe: {}
    startupProbe: {}

  configmap:
    data:
      CLOUD_ENVIRONMENT: "production"
      FRONTEGG_METRICS_ENABLED: "false"
      FRONTEGG_JAEGER_ENABLED: "true"
      NODE_ENV: "production"
      LOG_LEVEL: "verbose"
      #SENTRY_ENABLED: "true"
      FRONTEGG_CONFIG_DIRECTORY: "/etc/config"
      FRONTEGG_SPLIT_IO_USE_SYNCHRONIZER: "false"

  configuration:
    map:
      config-center:
        FRONTEGG_ENV_ID: env-id
        FRONTEGG_ADMINS_SERVICE_URL: admins-service-url
        FRONTEGG_AUDITS_SERVICE_URL: audits-service-url
        FRONTEGG_AUTHENTICATION_SERVICE_URL: authentication-service-url
        FRONTEGG_METADATA_SERVICE_URL: metadata-service-url
        FRONTEGG_NOTIFICATION_SERVICE_URL: notification-service-url
        FRONTEGG_REPORTS_ENGINE_URL: reports-engine-url
        FRONTEGG_REPORTS_SERVICE_URL: reports-service-url
        FRONTEGG_TEAM_SERVICE_URL: team-service-url
        FRONTEGG_VENDORS_SERVICE_URL: vendors-service-url
        FRONTEGG_ENV_DUPLICATOR_URL: env-duplicator-service-url
        FRONTEGG_USAGE_TRACKING_URL: usage-tracking-service-url
        FRONTEGG_TENANT_SERVICE_URL: tenants-service-url
        FRONTEGG_WEBPUSH_SERVICE_URL: webpush-service-url
        FRONTEGG_WEBHOOK_SERVICE_URL: webhook-service-url
        FRONTEGG_EVENT_SERVICE_URL: events-service-url
        FRONTEGG_INTEGRATIONS_SERVICE_URL: integrations-service-url
        FRONTEGG_IDENTITY_SERVICE_URL: identity-service-url
        FRONTEGG_IDENTITY_P1_SERVICE_URL: identity-p1-service-url
        FRONTEGG_OAUTH_SERVICE_URL: oauth-service-url
        FRONTEGG_POLICY_SERVICE_URL: policy-service-url
        FRONTEGG_SUBSCRIPTIONS_SERVICE_URL: subscriptions-service-url
        FRONTEGG_PREHOOK_SERVICE_URL: prehook-service-url
        FRONTEGG_DASHBOARD_ENV_BUILDER_URL: dashboard-env-builder-url
        FRONTEGG_BACKOFFICE_SERVICE_URL: backoffice-service-url
        FRONTEGG_PRICING_VIEWS_URL: pricing-views-url
        FRONTEGG_DIRECTORY_SERVICE_URL: directory-service-url
        FRONTEGG_LOGS_SERVICE_URL: logs-service-url
        FRONTEGG_LOGS_STREAMING_SERVICE_URL: logs-streaming-service-url
        FRONTEGG_ENTITLEMENTS_SERVICE_URL: entitlements-service-url
        FRONTEGG_SECURITY_ENGINES_SERVICE_URL: security-engines-url
        FRONTEGG_APPLICATIONS_SERVICE_URL: applications-service-url
        FRONTEGG_CUSTOM_CODE_SERVICE_URL: custom-code-service-url
        FRONTEGG_SECURITY_CENTER_SERVICE_URL: security-center-service-url
        FRONTEGG_SIGNALS_SERVICE_URL: signals-service-url
        FRONTEGG_AUTH_HUB_URL: auth-hub-service-url
        FRONTEGG_NLP_EXECUTION_ASSISTANT_URL: nlp-execution-assistant-url
        FRONTEGG_ENTITLEMENTS_AGENT_URL: entitlements-agent-url
        CORS_ORIGINS: cors-origin
        FRONTEGG_JAEGER_ENDPOINT: tracing-collector-endpoint
        FRONTEGG_USAGE_REPORTING_ENABLED: api-gateway-usage-reporting-enabled
        FRONTEGG_USAGE_REPORTING_KAFKA_TOPIC_NAME: tenants-usage-reporting-topic-name
        FRONTEGG_METRICS_ENABLED: api-gateway-metrics-enabled
        FRONTEGG_ENABLE_MULTI_HOST: enable-multi-hosts
        FRONTEGG_REDIS_DB_INDEX: api-gateway-redis-db-index
        FRONTEGG_ENABLE_REDIS_STORE: api-gateway-enable-redis-store
        IGNORED_HOSTS: api-gateway-ignore-hosts

  externalSecret:
    enabled: true
    mountPath: /etc/config/config.yaml
    text: |
      {{- $secret := .contents | fromYaml}}
      apiKey: {{ $secret.frontegg.apiKeys.apiGatewayApiKey | toYaml }}
      fronteggClientId: {{ $secret.frontegg.xxx.fronteggClientId | toYaml }}
      encryptionSecret: {{ $secret.frontegg.applications.apiGateway.apiGatewayEncryptionSecret | toYaml }}
      customDomains:
        secretHeader: {{ $secret.frontegg.customDomains.secretHeader | toYaml }}
      redis:
        host: {{ $secret.databases.redis.host | toYaml }}
        port: {{ $secret.databases.redis.port | toYaml }}
        password: {{ $secret.databases.redis.password | toYaml }}
        tls: {{ $secret.databases.redis.tls | toYaml }}
      sentryDsn: {{ $secret.externalServices.sentry.dsn | toYaml }}
      publicKey: {{ $secret.frontegg.xxx.authPublicKey | toYaml }}
      identityPublicKey: {{ $secret.frontegg.applications.identity.publicKey | toYaml }}
      splitIO:
        key: {{ $secret.externalServices.split.sdkKey | toYaml }}
        redis:
          host: {{ $secret.databases.redis.host | toYaml }}
          port: {{ $secret.databases.redis.port | toYaml }}
          password: {{ $secret.databases.redis.password | toYaml }}
      kafka:
        brokerList: {{ $secret.databases.kafka.brokerList | toYaml }}
        saslPassword: {{ $secret.databases.kafka.saslPassword | toYaml }}
        saslUsername: {{ $secret.databases.kafka.saslUserName | toYaml }}
      proxy:
        authentication:
          apiKey: {{ $secret.frontegg.apiKeys.authenticationServiceApiKey | toYaml }}
        vendors:
          apiKey: {{ $secret.frontegg.apiKeys.vendorsServiceApiKey | toYaml }}
        audits:
          apiKey: {{ $secret.frontegg.apiKeys.auditsServiceApiKey | toYaml }}
        team:
          apiKey: {{ $secret.frontegg.apiKeys.teamManagementApiKey | toYaml }}
        admins:
          apiKey: {{ $secret.frontegg.apiKeys.adminsServiceApiKey | toYaml }}
        metadata:
          apiKey: {{ $secret.frontegg.apiKeys.metadataServiceApiKey | toYaml }}
        reportsService:
          apiKey: {{ $secret.frontegg.apiKeys.reportsServiceApiKey | toYaml }}
        reportsEngine:
          apiKey: {{ $secret.frontegg.apiKeys.reportsEngineApiKey | toYaml }}
        notifications:
          apiKey: {{ $secret.frontegg.apiKeys.notificationServiceApiKey | toYaml }}
        webpush:
          apiKey: {{ $secret.frontegg.apiKeys.webpushServiceApiKey | toYaml }}
        events:
          apiKey: {{ $secret.frontegg.apiKeys.eventsServiceApiKey | toYaml }}
        webhooks:
          apiKey: {{ $secret.frontegg.apiKeys.webhooksServiceApiKey | toYaml }}
        integrations:
          apiKey: {{ $secret.frontegg.apiKeys.integrationsServiceApiKey | toYaml }}
        tenants:
          apiKey: {{ $secret.frontegg.apiKeys.tenantsServiceApiKey | toYaml }}
        identity:
          apiKey: {{ $secret.frontegg.apiKeys.identityServiceApiKey | toYaml }}
        subscriptions:
          apiKey: {{ $secret.frontegg.apiKeys.subscriptionsServiceApiKey | toYaml }}
        oauth:
          apiKey: {{ $secret.frontegg.apiKeys.oauthServiceApiKey | toYaml }}
        policy:
          apiKey: {{ $secret.frontegg.apiKeys.policyServiceApiKey | toYaml }}
        prehooks:
          apiKey: {{ $secret.frontegg.apiKeys.prehookApiKey | toYaml }}
        envDuplicator:
          apiKey: {{ $secret.frontegg.apiKeys.envDuplicatorApiKey | toYaml }}
        usageTracking:
          apiKey: {{ $secret.frontegg.apiKeys.usageTrackingApiKey | toYaml }}
        dashboardEnvBuilder:
          apiKey: {{ $secret.frontegg.apiKeys.dahboardEnvBuilderApiKey | toYaml }}
        backoffice:
          apiKey: {{ $secret.frontegg.apiKeys.backofficeApiKey | toYaml }}
        pricingViews:
          apiKey: {{ $secret.frontegg.apiKeys.pricingViewsApiKey | toYaml }}
        directoryService:
          apiKey: {{ $secret.frontegg.apiKeys.directoryServiceApiKey | toYaml }}
        logsService:
          apiKey: {{ $secret.frontegg.apiKeys.logsServiceApiKey | toYaml }}
        logsStreamingService:
          apiKey: {{ $secret.frontegg.apiKeys.logsStreamingServiceApiKey | toYaml }}
        entitlementsService:
          apiKey: {{ $secret.frontegg.apiKeys.entitlementsServiceApiKey | toYaml }}
        securityEngines:
          apiKey: {{ $secret.frontegg.apiKeys.securityEnginesApiKey | toYaml }}
        securityCenter:
          apiKey: {{ $secret.frontegg.apiKeys.securityCenterServiceApiKey | toYaml }}
        signals:
          apiKey: {{ $secret.frontegg.apiKeys.signalsServiceApiKey | toYaml }}
        applicationsService:
          apiKey: {{ $secret.frontegg.apiKeys.applicationsServiceApiKey | toYaml }}
        customCodeService:
          apiKey: {{ $secret.frontegg.apiKeys.customCodeServiceApiKey | toYaml }}
        authHub:
          apiKey: {{ $secret.frontegg.apiKeys.authHubServiceApiKey | toYaml }}
        nlpExecutionAssistant:
          apiKey: {{ $secret.frontegg.apiKeys.nlpExecutionAssistantApiKey | toYaml }}
    additionalSecrets: ""