{{- if eq .Values.deploymentMode "separateDeployments" }}
# PDPAgent Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-pdpAgent
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: pdpAgent
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pdpAgent
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: pdpAgent
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-pdpAgent
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.pdpAgent.repository }}:{{ .Values.pdpAgent.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.pdpAgent.pullPolicy }}
          {{- if .Values.env.pdpAgent }}
          env:
            {{- range $key, $value := .Values.env.pdpAgent }}
            - name: {{ include "toEnvVarName" $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources.pdpAgent }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
# MCP Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-mcp-server
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: mcpServer
spec:
  replicas: {{ .Values.mcpServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mcpServer
  template:
    metadata:
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mcpServer
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-mcp-server
          securityContext:
            capabilities:
              drop:
              - NET_RAW
          image: "{{ .Values.mcpServer.repository }}:{{ .Values.mcpServer.tag }}"
          imagePullPolicy: {{ .Values.mcpServer.pullPolicy }}
          env:
            {{- if .Values.env.mcpServer }}
            {{- range $key, $value := .Values.env.mcpServer }}
            - name: {{ include "toEnvVarName" $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- else }}
            - name: PDP_URL
              value: "http://{{ include "fullname" . }}-pdpAgent:8181"
            {{- end }}
          ports:
            - name: http
              containerPort: 8182
              protocol: TCP
          {{- with .Values.resources.mcpServer }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
