---
# SpiceDB Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-spicedb
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: spicedb
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.spicedb.port }}
      targetPort: {{ .Values.service.spicedb.targetPort }}
      protocol: {{ .Values.service.spicedb.protocol }}
      name: grpc
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: spicedb
{{- if not .Values.cockroachdb.operator.enabled }}
---
# CockroachDB Service (only for manual StatefulSet deployment)
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-cockroachdb
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: cockroachdb
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.cockroachdb.port }}
      targetPort: {{ .Values.service.cockroachdb.targetPort }}
      protocol: {{ .Values.service.cockroachdb.protocol }}
      name: grpc
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cockroachdb
---
# CockroachDB Headless Service (only for manual StatefulSet deployment)
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-cockroachdb-headless
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: cockroachdb
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.cockroachdb.port }}
      targetPort: {{ .Values.service.cockroachdb.targetPort }}
      protocol: {{ .Values.service.cockroachdb.protocol }}
      name: grpc
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cockroachdb
{{- end }}
---
# MCP Server Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-mcp-server
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.mcpServer.port }}
      targetPort: {{ .Values.service.mcpServer.targetPort }}
      protocol: {{ .Values.service.mcpServer.protocol }}
      name: http
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server