apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8181
      targetPort: http
      protocol: TCP
      name: http
    - port: 8182
      targetPort: http-mcp-server
      protocol: TCP
      name: http-mcp-server
  selector:
    {{- include "selectorLabels" . | nindent 4 }}