{{- if .Values.albIngress.enabled -}}
{{- $fullName := include "api-gateway.fullname" . -}}
{{- $name := include "api-gateway.name" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-alb-ingress
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }} # check this in _helper
  {{- with .Values.albIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.albIngress.ingressClassName }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  rules:
    - host: {{ include "api-gateway.hostname" . | quote }}
      http:
        paths:
        - path: /
          backend:
            service:
              name: frontegg-{{ $name }}
              port:
                number: {{ $svcPort }}
          pathType: ImplementationSpecific
{{- end }}