{{- if .Values.jobs.restart.enabled -}}
# allow getting status and patching only the one deployment you want
# to restart
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "api-gateway.jobs.restart.name" . }}
  labels:
      {{- include "api-gateway.labels" . | nindent 4 }}
  {{- with .Values.jobs.restart.role.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: [ "{{ include "api-gateway.fullname" . }}-deployment"]
    verbs: ["get", "patch", "list", "watch"] # "list" and "watch" are only needed
    # if you want to use `rollout status`
{{- end }}
