{{- if .Values.ingress.enabled -}}
{{- $fullName := include "fastify-api-gateway.fullname" . -}}
{{- $name := include "fastify-api-gateway.name" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $values := .Values }}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
    {{- include "fastify-api-gateway.labels" . | nindent 4 }} # check this in _helper
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        {{- range $host := .Values.ingress.hosts }}
        {{- if $host.tls }}
        - {{ $host.name | quote }}
        {{- end }}
        {{- end }}
      secretName: {{ $values.ingress.tls.secretName }}s
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host.name | quote }}
      http:
        paths:
          - path: /
            backend:
              service:
                name: frontegg-{{ $name }}
                port:
                  number: {{ $svcPort }}
            pathType: ImplementationSpecific
    {{- end }}
  {{- end }}

