apiVersion: v1
kind: Service
metadata:
  name: {{ include "bull-exporter.fullname" . }}-bull-exporter
  labels:
    app: bull
    role: exporter {{- include "bull-exporter.labels" . | nindent 4 }}
  annotations:
    prometheus.io/port: "9538"
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.bullExporter.type }}
  selector:
    app: bull
    role: exporter {{- include "bull-exporter.selectorLabels" . | nindent 4 }}
  ports: {{- .Values.bullExporter.ports | toYaml | nindent 2 -}}