{{- if .Values.externalSecret }}
{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "identity-service.fullname" . }}-external-secret
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-4"
    helm.sh/hook-delete-policy: "before-hook-creation"
  labels:
  {{- include "identity-service.labels" . | nindent 4 }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: external-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ include "identity-service.fullname" . }}-external-secret
    template:
      engineVersion: v2
      data:
        config: |
          {{- .Values.externalSecret.text | toString | nindent 10}}
  data:
    - secretKey: contents
      remoteRef:
        key: {{ .Values.componentsCollectionIdentifier }}
  {{- end }}
  {{- end }}
