apiVersion: v1
kind: Secret
metadata:
  name: {{ include "identity-service.fullname" . }}-secret
  labels:
  {{- include "identity-service.labels" . | nindent 4 }}
data:
  {{- with .Values.database }}
  FRONTEGG_IDENTITY_SERVICE_DB_HOST: {{ required "A valid .Values.database.host entry required!" .host | b64enc | quote }}
  FRONTEGG_IDENTITY_SERVICE_DB_USERNAME: {{ required "A valid .Values.database.username entry required!" .username | b64enc | quote }}
  FRONTEGG_IDENTITY_SERVICE_DB_PASSWORD: {{ required "A valid .Values.database.password entry required!" .password | b64enc | quote }}
  FRONTEGG_IDENTITY_SERVICE_DB_USE_SSL: {{ required "A valid .Values.database.ssl entry required!" .ssl | b64enc | quote }}
  FRONTEGG_IDENTITY_SERVICE_DB_NAME: {{ required "A valid .Values.database.name entry required!" .name | b64enc | quote }}
  {{- end }}
  {{- with .Values.redis }}
  FRONTEGG_IDENTITY_SERVICE_REDIS_HOST: {{ required "A valid .Values.redis.host entry required!" .host | b64enc | quote }}
  FRONTEGG_IDENTITY_SERVICE_REDIS_PASSWORD: {{ required "A valid .Values.redis.password entry required!" .password | b64enc | quote }}
  FRONTEGG_IDENTITY_SERVICE_REDIS_PORT: {{ required "A valid .Values.redis.port entry required!" .port | b64enc | quote }}
  FRONTEGG_IDENTITY_SERVICE_REDIS_TLS: {{ required "A valid .Values.redis.tls entry required!" .tls | b64enc | quote }}
  {{- end }}
  FRONTEGG_SENDGRID_API_KEY: {{ required "A valid .Values.email.apiKey entry required!" .Values.email.apiKey | b64enc | quote }}

  {{- with .Values.frontegg }}
  FRONTEGG_CLIENT_ID: {{ required "A valid .Values.frontegg.clientId entry required!" .clientId | b64enc | quote }}
  FRONTEGG_API_KEY: {{ required "A valid .Values.frontegg.apiKey entry required!" .apiKey | b64enc | quote }}
  FRONTEGG_AUTHENTICATION_URL: {{ required "A valid .Values.frontegg.authenticationUrl entry required!" .authenticationUrl | b64enc | quote }}
  FRONTEGG_MANAGED_IDENTITY_SERVICE_URL: {{ required "A valid .Values.frontegg.managedIdentityServiceUrl entry required!" .managedIdentityServiceUrl | b64enc | quote }}
  FRONTEGG_IDENTITY_SERVICE_EMAIL_TEMPLATE_REDIRECT_URL: {{ .emailTemplateRedirectUrl | b64enc | quote }}
  {{- with .sync }}
  FRONTEGG_IDENTITY_SERVICE_HYBRID_AUTH_RETRY_DELAY_MS: {{ required "A valid .Values.frontegg.sync.authenticationRetryDelay entry required!" .authenticationRetryDelay | b64enc | quote }}
  FRONTEGG_IDENTITY_SERVICE_HYBRID_SHUTDOWN_ON_INITIAL_AUTH_FAILURE: {{ required "A valid .Values.frontegg.sync.shutdownOnAuthenticationFailure entry required!" .shutdownOnAuthenticationFailure | b64enc | quote }}
  FRONTEGG_IDENTITY_SERVICE_HYBRID_SYNC_ENABLED: {{ required "A valid .Values.frontegg.sync.enabled entry required!" .enabled | b64enc | quote }}
  FRONTEGG_IDENTITY_SERVICE_HYBRID_SYNC_INTERVAL_MINUTES: {{ required "A valid .Values.frontegg.sync.intervalTime entry required!" .intervalTime | b64enc | quote }}
  {{- end }}
  {{- end }}

  {{- with .Values.kafka }}
  FRONTEGG_AUDITS_KAFKA_TOPIC_NAME: {{ required "A valid .Values.kafka.topicName entry required!" .topicName | b64enc | quote }}
  FRONTEGG_KAFKA_BROKER_LIST: {{ required "A valid .Values.kafka.brokerList entry required!" .brokerList | b64enc | quote }}
  FRONTEGG_KAFKA_SASL_PASSWORD: {{ .password | b64enc | quote }}
  FRONTEGG_KAFKA_SASL_USERNAME: {{ .username | b64enc | quote }}
  {{- end }}
