{{- if .Values.highPriority.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontegg-{{ include "fuc.name" . }}-hp
  labels:
    monitoring-metrics: enabled
    {{- include "fuc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "fuc.hp.selectorLabels" . | nindent 4 }}
{{- end }}
