{{- if .Values.highPriority.enabled }}
{{- if .Values.highPriority.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hp.name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    {{- include "keda.annotations" . | nindent 4 }}
spec:
  scaleTargetRef:
    {{- if .Values.argoRollouts }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ include "hp.name" . }}
    {{- else }}
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hp.name" . }}
    {{- end }}
  {{- if not .Values.highPriority.autoscaling.scaledObject.enabled }}
  minReplicas: {{ .Values.highPriority.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.highPriority.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.highPriority.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.web.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.highPriority.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.web.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}