{{- if .Values.highPriority.enabled }}
{{- if .Values.web.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "fuc.name" . }}-hp
  labels:
  {{- include "fuc.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    {{- if .Values.argoRollouts }}
    apiVersion : argoproj.io/v1alpha1
    kind : Rollout
    name : {{ include "fuc.name" . }}-rollout-hp
    {{- else }}
    apiVersion : apps/v1
    kind : Deployment
    name : {{ include "fuc.name" . }}-deployment-hp
    {{- end }}
  minReplicas: {{ (index .Values.highPriorityMinReplicasOverride .Values.componentsCollectionIdentifier).minReplicas | default .Values.highPriority.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.highPriority.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.highPriority.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.web.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.highPriority.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.web.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
