{{- if .Values.highPriority.enabled }}
{{- if .Values.argoRollouts }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "unified.name" . }}-rollout-hp
spec:
  workloadRef: # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "unified.name" . }}-deployment-hp
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "unified.hp.selectorLabels" . | nindent 6 }}
  strategy:
    blueGreen:
      activeService: {{ include "unified.hp.svc.name" . }}
      autoPromotionEnabled: true
{{- end }}
{{- end }}
