{{- if .Values.hp.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hp.name" . }}
  labels:
    monitoring-metrics: enabled
    {{- include "hp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ required "need to know if someone listening: .targetPort is required" .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "hp.selector.labels" . | nindent 4 }}
{{- end }}
