# Default values for entitlements-agent with SpiceDB
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# SpiceDB container configuration
spicedb:
  repository: authzed/spicedb
  tag: latest
  pullPolicy: IfNotPresent
  replicaCount: 1

  # SpiceDB configuration
  datastore:
    engine: cockroachdb
    # Connection URI will be constructed from cockroachdb config

  # GRPC preshared key for authentication
  grpcPresharedKey: spicedb

  # Log level
  logLevel: trace

# CockroachDB configuration
cockroachdb:
  repository: cockroachdb/cockroach
  tag: latest
  pullPolicy: IfNotPresent
  replicaCount: 1

  # Storage configuration
  persistence:
    enabled: true
    storageClass: ""
    size: 20Gi

# SpiceDB Sync container configuration
spicedbSync:
  repository: frontegg/entitlements-agent-spicedb-sync # Assuming this is where the sync image will be
  tag: 65ef073
  pullPolicy: IfNotPresent
  replicaCount: 1

  # Sync configuration
  config:
    # ZED CLI keyring password
    zedKeyringPassword: spicedb-sync-keyring

    # Log persistence
    logPersistence:
      enabled: true
      storageClass: ""
      size: 5Gi

# MCP Server container configuration
mcpServer:
  repository: frontegg/entitlements-agent-mcp-server
  pullPolicy: IfNotPresent
  tag: 65ef073
  replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - NET_RAW
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP

  # SpiceDB service configuration
  spicedb:
    port: 50051
    targetPort: 50051
    protocol: TCP

  # CockroachDB service configuration
  cockroachdb:
    port: 26257
    targetPort: 26257
    protocol: TCP

  # MCP Server service configuration
  mcpServer:
    port: 8182
    targetPort: 8182
    protocol: TCP

resources:
  spicedb:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      memory: 1Gi

  cockroachdb:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      memory: 2Gi

  spicedbSync:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      memory: 512Mi

  mcpServer:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      memory: 500Mi

# Health check configurations
healthChecks:
  spicedb:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3

  cockroachdb:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  spicedbSync:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

# Environment variables configuration
env:
  # Frontegg Configuration (for SpiceDB Sync)
  spicedbSync:
    fronteggClientId: "" # Required: Set your Frontegg Client ID
    fronteggClientSecret: "" # Required: Set your Frontegg Client Secret
    fronteggUrl: "https://api.albert-einstein.venv.life"

  # SpiceDB Configuration
  spicedb:
    spicedbGrpcPresharedKey: spicedb

  # CockroachDB Configuration
  cockroachdb:
    pguser: root
    pgpassword: password
    pgdatabase: spicedb

  # MCP Server Configuration
  mcpServer:
    spicedbAddress: "spicedb:50051" # Will be constructed based on service name
    spicedbToken: spicedb

# Database initialization jobs
initJobs:
  # Enable database creation and migration jobs
  enabled: true

  # Job configuration
  restartPolicy: Never
  backoffLimit: 3

  # Resources for init jobs
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi
