{{ $values := .Values }}
{{- $debezium := $values.debezium }}
{{- $top := $ }}
{{- if .Values.debezium.enabled }}
{{- if not .Values.debezium.secret.name }}
{{ fail ".Values.debezium.secret.name must be set" }}
{{- end }}
{{- if .Values.debezium.secret }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: debezium-secret
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-20"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: external-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.debezium.secret.name }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data: 
        brokerList: |
          {{`{{ $secret := .raw_yaml  | fromYaml }}`}} 
          {{`{{- $secret.databases.kafka.brokerList | toYaml -}}`}}
  data:
    - secretKey: raw_yaml
      remoteRef:
        key: {{ .Values.initDbJob.secret.remoteRefKey }}
{{- end }}
{{- end }}
