name: identity

envID: test-local

image:
  repository: frontegg/identity-service

appVersion: staging-20240521.173819-eba032b

service:
  targetPort: 3003

worker:
  autoscaling:
    enabled: true
    minReplicas: 4
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 75

serviceAccount:
  enabled: true
  annotations:
    someshit/knuckle: enabled
