# Default values for frontegg unified chart.

# required
# serviceName: my-new-awesome-service
# team: my-team-of-imbeciles

componentsCollectionIdentifier: local

minReplicasOverride:
  {}
  # prd-ap-se2:
  #   minReplicas: 3

highPriorityMinReplicasOverride:
  {}
  # prd-ap-se2:
  #   minReplicas: 2

appVersion: master-latest
argoRollouts: true

web:
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 75
  podAnnotations: {}
  resources: {}
  terminationGracePeriodSeconds: 30
  # handles restart (not offline)
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 40
    periodSeconds: 60
  # decides when to forward requests (not offline)
  readinessProbe:
    failureThreshold: 1
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
  nodeSelector: {}
  tolerations: []
  affinity: {}

offline:
  enabled: false

image:
  repository:
  pullPolicy: Always

revisionHistoryLimit: 3

imagePullSecrets:
  - name: regcred

service:
  type: ClusterIP

jobs: {}

configmap:
  data: {}

configuration:
  map:
    config-center:

externalSecret:
  enabled: false
  text: |
    {{- $secret := .contents | fromYaml}}
    apiKey: {{ $secret.frontegg.apiKeys.tenantsServiceApiKey| default "x" }}
  additionalSecrets: ""

prometheusRule:
  enabled: false

ingress:
  enabled: false

albIngress:
  enabled: false

highPriority:
  enabled: false
  labels:
    priority: "high"
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 75

doubleSVC:
  - security-engines
  - reporting-scheduler
  - api-gateway
  - dashboard
  - forward-proxy
