# Default values for frontegg unified chart.

# required
# name: my-new-awesome-service
# team: my-team-of-imbeciles
# envID: local

# CAUTION this will change name of all manifests
nameSuffix: v2

# appVersion is required
# appVersion: master-latest

argoRollouts: true

image:
  repository:

revisionHistoryLimit: 3

imagePullPolicy: Always

imagePullSecrets:
  - name: regcred

service:
  labels:
    monitoring-metrics: enabled
  type: ClusterIP
  protocol: TCP
  port: 80

web:
  enabled: false
  command: ["/bin/bash"]
  args: ["entrypoint.sh", "service"]
  env:
    # - name: FRONTEGG_IS_SERVICE_OFFLINE_PROCESS
    #   value: "false"
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 75
  podAnnotations: {}
  resources: {}
  terminationGracePeriodSeconds: 30
  # handles restart (not offline)
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 40
    periodSeconds: 60
  # decides when to forward requests (not offline)
  readinessProbe:
    failureThreshold: 1
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
  nodeSelector: {}
  tolerations: []
  affinity: {}

worker:
  enabled: false
  command: ["/bin/bash"]
  args: ["entrypoint.sh", "worker"]
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 75
    scaledObject:
      enabled: false
  env:
    # - name: FRONTEGG_IS_SERVICE_OFFLINE_PROCESS
    #   value: "true"
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 40
    periodSeconds: 60
  # decides when to forward requests (not offline)
  readinessProbe:
    failureThreshold: 1
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
  nodeSelector: {}
  tolerations: []
  affinity: {}

highPriority:
  enabled: false
  labels:
    priority: "high"
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 75
    scaledObject:
      enabled: false
      triggers: []
        - type: cpu
          metadata:
            type: Utilization
            value: "80"
        - type: memory
          metadata:
            type: Utilization
            value: "75"
        - type: prometheus
          name: P90 latency
          metadata:
            serverAddress: http://vmselect-vm.observability.svc.cluster.local:8481/select/0/prometheus
            query: max(histogram_quantile(0.90, sum(rate(route_response_latency_ms_bucket{direction="inbound",namespace="frontegg", pod=~"identity-identity-service-rollout-hp.*"}[1m]) ) by (le, pod)))
            threshold: "1000"
        - type: prometheus
          name: eventloop lag
          metadata:
            serverAddress: http://vmselect-vm.observability.svc.cluster.local:8481/select/0/prometheus
            query: sum(nodejs_eventloop_lag_seconds{pod=~"identity-identity-service-rollout-hp.*"})
            threshold: "1"
        - type: prometheus
          name: active handlers
          metadata:
            serverAddress: http://vmselect-vm.observability.svc.cluster.local:8481/select/0/prometheus
            query: max(nodejs_active_handles_total{pod=~"identity-identity-service-rollout-hp.*"}[5m])
            threshold: "750"
      advanced:
        horizontalPodAutoscalerConfig: # Optional. Section to specify HPA related options
          name: identity-identity-service-hp-rollout-hpa
          behavior:
            scaleDown:
              stabilizationWindowSeconds: 300
              policies:
                - type: Pods
                  value: 1
                  periodSeconds: 60
            scaleUp:
              stabilizationWindowSeconds: 0
              policies:
                - type: Pods
                  value: 3
                  periodSeconds: 10

jobs:
  # migrate:
  #   enabled: true
  #   metadata:
  #     annotations:
  #       argocd.argoproj.io/sync-wave: "-500"
  #   spec:
  #     command: ["/bin/bash"]
  #     args: ["run-migrations.sh"]
  #     resources:
  #       requests:
  #         cpu: 500m
  #         memory: 500Mi

cronjobs:
  refresh:
    enabled: false
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-500"
    command: ["/bin/bash"]
    args: ["entrypoint.sh"]
    schedule: "0 * * * *"
    ttlSecondsAfterFinished: 600
    concurrencyPolicy: Replace
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 1
    restartPolicy: Never
    nodeSelector: {}

configmap:
  annotations:
    # argocd.argoproj.io/sync-wave: "-1000"
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-2"
    helm.sh/hook-delete-policy: "before-hook-creation"
  data:
    # EXAMPLE: '{{ include "fullname" $ }}-example'

configuration:
  map:
    config-center:

externalSecret:
  enabled: false
  mountPath: /etc/config/config.yaml
  subPath: config
  refreshInterval: 1m
  annotations:
    # argocd.argoproj.io/sync-wave: "-1000"
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-4"
    helm.sh/hook-delete-policy: "before-hook-creation"
  text: |
    {{- $secret := .contents | fromYaml }}
    apiKey: {{ $secret.frontegg.apiKeys.tenantsServiceApiKey| default "x" }}
  additionalSecrets: ""

prometheusRule:
  enabled: false
  namespace: observability
  labels:
    release: prometheus
  rpsAlertLimit: 50
  rules:
    - alert: EXAMPLE
      expr: |
        round(sum(irate(nginx_ingress_controller_requests{ingress="{{ include "unified.name" . }}-ingress"}[2m])) , 0.001) > {{ .Values.prometheusRule.rpsAlertLimit }}
      for: 1m
      labels:
        severity: critical
      annotations:
        description: EXAMPLE RPS is higher then {{ .Values.prometheusRule.rpsAlertLimit }} for 2 minutes or more
        summary: EXAMPLE RPS is higher than {{ .Values.prometheusRule.rpsAlertLimit }}

ingress:
  enabled: true
  ingressClassName: nginx
  hostnameOverride: "example.changeme"
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* ^/(metrics|health) {
        deny all;
        return 403;
      }
  tls:
    enabled: false
    secretName: frontegg-secret-2020

albIngress:
  enabled: true
  ingressClassName: nginx2
  hostnameOverride: ""
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* ^/(metrics|health) {
        deny all;
        return 403;
      }

highPriority:
  enabled: false
  command: ["/bin/bash"]
  args: ["entrypoint.sh", "service"]
  env:
    # - name: FRONTEGG_IS_SERVICE_OFFLINE_PROCESS
    #   value: "false"
  labels:
    priority: "high"
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 75

serviceProfile:
  # routes:
  #   - condition:
  #       method: EXAMPLE
  #       pathRegex: /example/test/
  #     name: EXAMPLE /example/test/

# additional helm templates to render resources freely
additionalTemplates: |

# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: {{ include "fullname" $ }}-sa
#   labels:
#     {{- include "unified.labels" $ | nindent 4 }}

keda:
  annotations:
    scaledobject.keda.sh/transfer-hpa-ownership: "true"
    validations.keda.sh/hpa-ownership: "false"

serviceAccount:
  enabled: false
  annotations: {}
