# Default values for frontegg unified chart.

# required
# serviceName: my-new-awesome-service
# team: my-team-of-imbeciles

componentsCollectionIdentifier: local

minReplicasOverride:
  {}
  # prd-ap-se2:
  #   minReplicas: 3

highPriorityMinReplicasOverride:
  {}
  # prd-ap-se2:
  #   minReplicas: 2

replicaCount: 1
appVersion: master-latest
argoRollouts: true

offline:
  enabled: false
  podAnnotations:
    linkerd.io/inject: disabled
  replicaCount: 1
  nodeSelector:
    workload: general
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 75
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
  # handles restart
  livenessProbe:
    failureThreshold: 5
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 60
    periodSeconds: 60

  # decides when to forward requests
  readinessProbe:
    failureThreshold: 1
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5

image:
  repository:
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

podAnnotations:
  linkerd.io/inject: enabled

podSecurityContext: {}
# fsGroup: 2000

service:
  type: ClusterIP
  port: 80
  targetPort: 3015
  protocol: TCP
  name: http

jobs:
  migrate:
    enabled: true
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-500"
    spec:
      annotations: {}
      args:
        - "/bin/bash"
        - "./run-migrations.sh"
      resources:
        requests:
          cpu: 300m
          memory: 500Mi

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 75

# handles restart (not offline)
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 40
  periodSeconds: 60

# decides when to forward requests (not offline)
readinessProbe:
  failureThreshold: 1
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

nodeSelector: {}

tolerations: []

affinity: {}

configmap:
  data: {}

configuration:
  map:
    config-center:
      FRONTEGG_SPLIT_IO_USE_SYNCHRONIZER: splitio-synchronizer
externalSecret:
  enabled: false
  text: |
    {{- $secret := .contents | fromYaml}}
    apiKey: {{ $secret.frontegg.apiKeys.tenantsServiceApiKey| default "x" }}
  additionalSecrets: ""

prometheusRule:
  enabled: false
  namespace: observability
  labels:
    release: prometheus
  rpsAlertLimit: 300
  rules:
    - alert: ApiGatewayRequestRateIsTooHigh
      expr: |
        round(sum(irate(nginx_ingress_controller_requests{ingress="{{ include "fullname" . }}-ingress"}[2m])) , 0.001) > {{ .Values.prometheusRule.rpsAlertLimit }}
      for: 2m
      labels:
        severity: warning
      annotations:
        description: Api Gateway RPS is higher then {{ .Values.prometheusRule.rpsAlertLimit }} for 2 minutes or more
        summary: Api Gateway RPS is higher than {{ .Values.prometheusRule.rpsAlertLimit }}

ingress:
  enabled: false
  ingressClassName: nginx
  hostnameOverride: ""
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 4m
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_clear_input_headers "Host" "X-Forwarded-Host";
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Host $http_x_forwarded_host;
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header X-Request-ID $request_id;
      add_header Cache-Control "no-transform";
      location ~* ^/(metrics|healthcheck) {
        deny all;
        return 403;
      }
  tls:
    enabled: false
    secretName: frontegg-secret-2020
  hosts: []

albIngress:
  enabled: false
  ingressClassName: nginx2
  hostnameOverride: ""
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 4m
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_clear_input_headers "Host" "X-Forwarded-Host";
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Host $http_x_forwarded_host;
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header X-Request-ID $request_id;
      add_header Cache-Control "no-transform";
      location ~* ^/(metrics|healthcheck) {
        deny all;
        return 403;
      }

highPriority:
  enabled: false
  labels:
    priority: "high"
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 75
