apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-list-binding
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: pod-list
  apiGroup: rbac.authorization.k8s.io
