{{- define "common.deployment" -}}
{{- $deployment := .deployment -}}
{{- $conext := .context -}}
---
{{ tpl $deployment $conext }}

{{/*apiVersion: apps/v1*/}}
{{/*kind: Deployment*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "common-service.fullname" . }}-deployment*/}}
{{/*  labels:*/}}
{{/*  {{- include "common-service.labels" . | nindent 4 }}*/}}
{{/*  {{- with $deployment.labels }}*/}}
{{/*    {{- toYaml . | nindent 4 }}*/}}
{{/*  {{- end }}*/}}
{{/*spec:*/}}
{{/*  {{- if $deployment.argoRollouts }}*/}}
{{/*  replicas: 0*/}}
{{/*  {{- else if not $deployment.autoScaling.enabled }}*/}}
{{/*  replicas: {{ $deployment.replicaCount }}*/}}
{{/*  {{- end }}*/}}

{{- end -}}
