apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "integrations-service.fullname" . }}-deployment
  labels:
  {{- include "integrations-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "integrations-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "integrations-service.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ (print .Values.configmap) | sha256sum }}
        checksum/template.config-map: {{ include (print $.Template.BasePath "/config-map.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.externalSecret }}
      {{- if .Values.externalSecret.enabled }}
      volumes:
        - name: vol-secret
          secret:
            secretName: {{ include "integrations-service.fullname" . }}-external-secret
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.appVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.externalSecret }}
          {{- if .Values.externalSecret.enabled }}
          volumeMounts:
            - name: vol-secret
              mountPath: /etc/config/config.env
              subPath: config
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            {{- range $config_name, $values := .Values.configuration.map }}
            {{- range $key, $value :=  $values}}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $config_name }}
                  key: {{ $value }}
          {{- end }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "integrations-service.fullname" . }}-configmap
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
  {{- toYaml . | nindent 8 }}
  {{- end }}
