version: '3.8'

services:
  api-gateway:
    image: frontegg/hybrid-api-gateway:${API_GATEWAY_TAG}
    container_name: frontegg-api-gateway
    ports:
      - 9090:9090
    networks:
      - frontegg-network
    env_file:
      - ./.common.env
    environment:
      - FRONTEGG_AUTH_PUBLIC_KEY=
      - FRONTEGG_HYBRID_SERVICES=audits

  audits-service:
    image: frontegg/hybrid-audits-service:${AUDITS_SERVICE_TAG}
    container_name: frontegg-audits-service
    networks:
      - frontegg-network
    env_file:
      - ./.common.env
    environment:
      - FRONTEGG_PORT="3002"
      - FRONTEGG_KAFKA_BROKER_LIST=${KAFKA_BROKER_LIST}
      - FRONTEGG_KAFKA_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}
      - FRONTEGG_AUDITS_TOPIC_NAME=${AUDITS_TOPIC_NAME}
      - FRONTEGG_AUDITS_DB_TYPE=mysql
      - FRONTEGG_AUDITS_DB_HOST=${AUDITS_DB_HOST}
      - FRONTEGG_AUDITS_DB_USERNAME=${AUDITS_DB_USERNAME}
      - FRONTEGG_AUDITS_DB_PASSWORD=${AUDITS_DB_PASSWORD}
      - FRONTEGG_AUDITS_DB_NAME=${AUDITS_DB_NAME}
      - FRONTEGG_AUDITS_DB_USE_SSL=${AUDITS_DB_USE_SSL}
      - FRONTEGG_METADATA_SERVICE_FETCH_PUBSUB_STRATEGY="false"
      - FRONTEGG_CLIENT_ID=
      - FRONTEGG_API_KEY=
      - FRONTEGG_SPLIT_IO_KEY=''
      - FRONTEGG_AUDITS_SERVICE_HYBRID_AUTH_RETRY_DELAY_MS=5000
      - FRONTEGG_AUDITS_SERVICE_HYBRID_SHUTDOWN_ON_INITIAL_AUTH_FAILURE="true"
networks:
  frontegg-network:
    driver: bridge
