---
name: unified-chart release flow

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - common/unified-chart/**

concurrency:
  group: ${{ github.workflow }}

jobs:
  release-stg:
    uses: frontegg/helm-charts/.github/workflows/release-chart-version.yaml@master
    with:
      environment: staging
  release-ca-au:
    needs: release-stg
    uses: frontegg/helm-charts/.github/workflows/release-chart-version.yaml@master
    with:
      environment: production-au
  # release-au:
  #   needs: release-ca
  #   uses: frontegg/helm-charts/.github/workflows/release-chart-version.yaml@master
  #   with:
  #     environment: australia
  release-us:
    needs: release-au
    uses: frontegg/helm-charts/.github/workflows/release-chart-version.yaml@master
    with:
      environment: production-us
  release-eu:
    needs: release-us
    uses: frontegg/helm-charts/.github/workflows/release-chart-version.yaml@master
    with:
      environment: production-global
