---
name: unified-chart release flow

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - common/unified-chart/**

jobs:
  stg:
    uses: frontegg/helm-charts/.github/workflows/release-chart-version.yaml@master
    with:
      environment: staging
  ca-au:
    needs: stg
    uses: frontegg/helm-charts/.github/workflows/release-chart-version.yaml@master
    with:
      environment: production-au
  us:
    needs: ca-au
    uses: frontegg/helm-charts/.github/workflows/release-chart-version.yaml@master
    with:
      environment: production-us
  eu:
    needs: us
    uses: frontegg/helm-charts/.github/workflows/release-chart-version.yaml@master
    with:
      environment: production-global
