---
name: release chart single version
permissions: write-all
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      charts-dir:
        required: false
        type: string
        default: common
      chart-name:
        required: false
        type: string
        default: unified-chart

jobs:
  release-chart:
    permissions:
      contents: write
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: package chart
        run: |
          cd ${{ inputs.charts-dir }}/${{ inputs.chart-name }}
          version=$(cat Chart.yaml | yq e '.version')
          helm package . --version $version-${{ inputs.environment }}
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: common
          skip_packaging: true
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
