---
name: release unified-chart flow

on:
  push:
    branches:
      - master

jobs:
  release-stg:
    uses: frontegg/helm-charts/.github/workflows/release-chart-version.yaml@master
    with:
      environment: stg
  release-ca:
    uses: frontegg/helm-charts/.github/workflows/release-chart-version.yaml@master
    with:
      environment: ca
