---
name: unified-chart release flow

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - common/unified-chart/**

concurrency:
  group: ${{ github.workflow }}

jobs:
  release-stg:
    uses: frontegg/helm-charts/.github/workflows/release-chart-version.yaml@master
    with:
      environment: stg
  release-ca:
    needs: release-stg
    uses: frontegg/helm-charts/.github/workflows/release-chart-version.yaml@master
    with:
      environment: canada
  release-au:
    needs: release-stg
    uses: frontegg/helm-charts/.github/workflows/release-chart-version.yaml@master
    with:
      environment: australia
  release-us:
    needs: release-stg
    uses: frontegg/helm-charts/.github/workflows/release-chart-version.yaml@master
    with:
      environment: production-us
  release-eu:
    needs: release-stg
    uses: frontegg/helm-charts/.github/workflows/release-chart-version.yaml@master
    with:
      environment: production-global
