{{- $top := . -}}
{{- $values := .Values -}}
{{- if $values.hp.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hp.name" $top }}
  labels:
  {{- include "hp.labels" $top | nindent 4 }}
  {{- toYaml $values.hp.labels | nindent 4 }}
spec:
  revisionHistoryLimit: {{ $values.revisionHistoryLimit | default 2 }}
  {{- if $values.argoRollouts.enabled }}
  replicas: 0
  {{- else if not $values.web.autoscaling.enabled }}
  replicas: {{ $values.hp.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hp.selector.labels" $top | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hp.labels" $top | nindent 8 }}
      annotations:
        checksum/secret: {{ printf "%s%s" (print $values.externalSecret.text) (print $values.externalSecret.additionalSecrets) | sha256sum }}
        {{- $valshp := $values.hp -}}
        {{- include "calculate.pod.annotations" $valshp | nindent 8 }}
    spec:
      {{- if $values.serviceAccount.enabled }}
      serviceAccountName: {{ include "service.account.name" $top }}
      {{- end }}
      terminationGracePeriodSeconds: {{ $values.hp.terminationGracePeriodSeconds | default 30 }}
      {{- with $values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or $values.externalSecret.enabled $values.hp.additionalVolumes }}
      volumes:
        {{- if $values.externalSecret.enabled }}
        - name: secret-volume
          secret:
            secretName: {{ include "secret.name" $top }}
        {{- end }}
        {{- with $values.hp.additionalVolumes }}
        {{- tpl . $top | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ include "container.name" $top }}
          {{- if $values.hp.image }}
          image: "{{ $values.hp.image.prefix }}{{ required "values.hp.image.name required" $values.hp.image.name }}:{{ required "values.hp.image.tag" $values.hp.image.tag }}"
          {{- else }}
          image: "{{ $values.image.prefix }}{{ required "what do you wanna run: .Values.image.repository must be set" $values.image.repository }}:{{ include "appVersion" $top }}"
          {{- end }}
          imagePullPolicy: {{ $values.imagePullPolicy }}
          {{- if or $values.externalSecret.enabled $values.hp.additionalVolumeMounts }}
          volumeMounts:
            {{- if $values.externalSecret.enabled }}
            {{- include "externalsecret.volumemount" $top | nindent 12 }}
            {{- end }}
            {{- with $values.hp.additionalVolumeMounts }}
            {{- tpl . $top | nindent 12 }}
            {{- end }}
          {{- end }}
          ports:
            {{- if $values.hp.ports }}
            {{- toYaml $values.hp.ports | nindent 12 }}
            {{- else }}
            - name: http
              containerPort: {{ $values.service.targetPort }}
              protocol: TCP
            {{- end }}
          {{- with $values.hp.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $values.hp.readinessProbe }}
          readinessProbe:
            successThreshold: {{ .successThreshold | default 5 }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $values.hp.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- include "container.env" $values.hp | indent 12 -}}
            {{- range $config_name, $keyValue := $values.configuration.map }}
            {{- range $key, $value :=  $keyValue }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $config_name }}
                  key: {{ $value }}
            {{- end }}
            {{- end }}
            {{- with $values.hp.vars }}
            {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
          {{- if $values.configmap.data }}
          envFrom:
            - configMapRef:
                name: {{ include "name" $top }}
            {{- with $values.hp.additionalEnvFrom }}
            {{- tpl . $top | nindent 12 }}
            {{- end }}
          {{- end }}
          resources:
            {{- required ".Values.hp.resources required" $values.hp.resources | toYaml | nindent 12 }}
          {{- with $values.hp.command }}
          command:
            {{- range . }}
            - {{ . | quote  }}
            {{- end }}
          {{- end }}
          {{- with $values.hp.args }}
          args:
            {{- range . }}
            - {{ . | quote  }}
            {{- end }}
          {{- end }}
      {{- with $values.hp.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $values.hp.affinity }}
      affinity:
        {{- tpl ($values.hp.affinity | toYaml) $top | toYaml | nindent 8 }}
      {{- else }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.frontegg.com/name
                      operator: In
                      values:
                        - {{ include "hp.name" $top }}
                topologyKey: "kubernetes.io/hostname"
      {{- end }}
      {{- with $values.hp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
