{{- $top := . -}}
{{- if .Values.hp.enabled }}
{{- if .Values.argoRollouts.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "hp.name" . }}
spec:
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hp.name" . }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "hp.selector.labels" . | nindent 6 }}
  strategy:
    {{- if .Values.argoRollouts.progressiveDelivery.enabled }}
    canary:
      {{- with .Values.argoRollouts.progressiveDelivery }}
      stableMetadata:
        {{- toYaml .stableMetadata | nindent 8 }}
      canaryMetadata:
        {{- toYaml .canaryMetadata | nindent 8 }}
      {{- end }}
      canaryService: {{ include "hp.name" . }}-canary
      stableService: {{ include "hp.name" . }}-stable
      trafficRouting:
        managedRoutes:
          - name: {{ include "hp.name" . }}
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: {{ include "hp.name" . }}-route
            useHeaderRoutes: true
            namespace: {{ .Release.Namespace }}
        {{- with .Values.argoRollouts.progressiveDelivery.steps }}
      steps:
        - setCanaryScale:
            replicas: {{ .replicas | default "1" }}
        - setHeaderRoute:
            name: {{ include "hp.name" $top }}
            match:
              - headerName: frontegg-trace-id
                headerValue:
                  prefix: automation
        - analysis:
            templates:
              - templateName: {{ include "hp.name" $top }}
            args:
              - name: service-name
                value: {{ include "githubrepo.name" $top }}
        - setHeaderRoute: # remove header route
            name: {{ include "hp.name"  $top  }}
        {{- end }}
    {{- else}}
    blueGreen:
    {{- with .Values.argoRollouts.activeMetadata }}
      activeMetadata:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      activeService: {{ include "hp.name" . }}
      autoPromotionEnabled: true
  {{- end }}
{{- end }}
{{- end }}


