{{- $top := . -}}
{{- $values := .Values -}}
{{- if .Values.hp.enabled }}
{{- if .Values.argoRollouts.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "hp.name" . }}
spec:
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hp.name" . }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "hp.selector.labels" . | nindent 6 }}
  strategy:
    {{- with .Values.argoRollouts.progressiveDelivery }}
    {{- if .enabled }}
    canary:
      {{- with .canaryMetadata }}
      canaryMetadata:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .stableMetadata }}
      stableMetadata:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      canaryService: {{ include "hp.name" $top }}-canary
      stableService: {{ include "hp.name" $top }}-stable
        trafficRouting:
          plugins:
            argoproj-labs/gatewayAPI:
              httpRoute: {{ include "hp.name" $top  }}
              namespace: "frontegg"
          steps:
            {{- toYaml .steps | nindent 12 }}
  {{- end }}
    {{- else}}
        blueGreen:
      {{- with .Values.argoRollouts.activeMetadata }}
      activeMetadata:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      activeService: {{ include "hp.name" . }}
      autoPromotionEnabled: true
    {{- end}}
{{- end }}
{{- end }}

