{{- if .Values.hp.enabled }}
{{- if .Values.argoRollouts.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "hp.name" . }}
spec:
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hp.name" . }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "hp.selector.labels" . | nindent 6 }}
  strategy:
    {{- if .Values.argoRollouts.progressiveDelivery.enabled }}
        canary:
        {{- with .Values.argoRollouts.progressiveDelivery }}
          stableMetadata:
          {{- toYaml .stableMetadata | nindent 12 }}
          canaryMetadata:
          {{- toYaml .canaryMetadata| nindent 12 }}
        {{- end }}
          canaryService: {{ include "hp.name" . }}-canary
          stableService: {{ include "hp.name" . }}-stable
          trafficRouting:
            plugins:
              argoproj-labs/gatewayAPI:
                httpRoute: {{ include "hp.name" . }}
                namespace: {{ .Release.Namespace }}
            {{- with .Values.argoRollouts.progressiveDelivery.steps }}
            steps:
              {{- toYaml . | nindent 12 }}
            {{- end }}
    {{- else}}
        blueGreen:
      {{- with .Values.argoRollouts.activeMetadata }}
      activeMetadata:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      activeService: {{ include "hp.name" . }}
      autoPromotionEnabled: true
    {{- end}}
{{- end }}
{{- end }}
