{{- if and .Values.secret.enabled (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "e10s-engine-sync.fullname" . }}
  labels:
    {{- include "e10s-engine-sync.labels" . | nindent 4 }}
type: Opaque
stringData:
  FRONTEGG_CLIENT_ID: {{ required ".Values.frontegg.clientId is required" .Values.frontegg.clientId | quote }}
  FRONTEGG_CLIENT_SECRET: {{ required ".Values.frontegg.clientSecret is required" .Values.frontegg.clientSecret | quote }}
  SPICEDB_GRPC_PRESHARED_KEY: {{ required ".Values.spicedb.presharedKey is required" .Values.spicedb.presharedKey | quote }}
  {{- with .Values.secret.additionalData }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}

