{{- if .Values.worker.enabled }}
{{- if .Values.argoRollouts }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "unified.worker.name" . }}
spec:
  workloadRef: # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "unified.worker.name" . }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "unified.workerSelectorLabels" . | nindent 6 }}
  strategy:
    blueGreen:
      activeService: {{ include "unified.worker.name" . }}
      autoPromotionEnabled: true
{{- end }}
{{- end }}