{{- if .Values.worker.enabled }}
{{- if .Values.argoRollouts }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unified.worker.name" . }}
  labels:
    monitoring-metrics: enabled
      {{- include "unified.workerLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "unified.workerSelectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}