{{- $values := .Values -}}
{{- $top := . -}}
{{- with $values.worker.autoscaling }}
{{- if .scaledObject.enabled }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "unified.worker.name" $top }}
  annotations:
    {{- include "keda-annotations" $top | nindent 4 }}
  labels:
    {{- include "unified.workerLabels" $top | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "unified.worker.name" $top }}
  minReplicaCount: {{.minReplicas }}
  maxReplicaCount: {{ .maxReplicas }}
  {{- with .scaledObject.fallback }}
  fallback:                                                 # Optional. Section to specify fallback options
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .scaledObject.triggers }}
  triggers:
    {{- toYaml . | nindent 4 }}
  {{- end}}
  {{- with .scaledObject.advanced }}
  advanced:
    {{- tpl ( . | toYaml) $ | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}