{{- $values := .Values -}}
{{- $top := . -}}
{{- with $values.worker.autoscaling }}
{{- if .enabled }}
{{- if .scaledObject.enabled }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "worker.name" $top }}
  annotations:
    {{- include "keda.annotations" $top | nindent 4 }}
  labels:
    {{- include "worker.labels" $top | nindent 4 }}
spec:
  scaleTargetRef:
    {{- if $values.argoRollouts }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ include "worker.name" $top }}
    {{- else }}
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "worker.name" $top }}
    {{- end }}
  minReplicaCount: {{.minReplicas }}
  maxReplicaCount: {{ .maxReplicas }}
  {{- with .scaledObject.fallback }}
  fallback:                                                 # Optional. Section to specify fallback options
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .scaledObject.triggers }}
  triggers:
    {{- toYaml . | nindent 4 }}
  {{- end}}
  {{- with .scaledObject.advanced }}
  advanced:
    {{- tpl ( . | toYaml) $ | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}