{{- if .Values.worker.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unified.name" . }}-worker-deployment
  labels:
  {{- include "unified.workerLabels" . | nindent 4 }}
spec:
  {{- if .Values.argoRollouts }}
  replicas: 0
  {{- else if not .Values.web.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  selector:
    matchLabels:
      {{- include "unified.workerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "unified.workerLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ (print .Values.configmap) | sha256sum }}
        {{- with .Values.worker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.worker.serviceAccountName }}
      serviceAccountName: {{ tpl . $ }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.worker.terminationGracePeriodSeconds | default 30 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.externalSecret.enabled }}
      volumes:
        - name: vol-secret
          secret:
            secretName: {{ include "external-secret-unique-name" . }}
      {{- end }}
      containers:
        - name: {{ include "unified.name" . }}-worker
          image: "{{ required ".Values.image.repository must be set" .Values.image.repository }}:{{ .Values.appVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if .Values.externalSecret.enabled }}
          volumeMounts:
            {{- include "unified.externalsecret.volumemount" . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }} # change this to 80 in the future
              protocol: TCP
          {{- with .Values.worker.livenessProbe }}
          livenessProbe:
          {{- . | toYaml | nindent  12 }}
          {{- end }}
          {{- with .Values.worker.readinessProbe }}
          readinessProbe:
          {{- . | toYaml | nindent  12 }}
          {{- end }}
          {{- with .Values.worker.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- include "unified.container.env" .Values.worker | nindent 12 }}
            {{- if .Values.externalSecret.enabled }}
            - name: FRONTEGG_CONFIG_DIRECTORY
              value: "/etc/config"
            {{- end }}
            {{- range $config_name, $values := .Values.configuration.map }}
            {{- range $key, $value :=  $values}}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $config_name }}
                  key: {{ $value }}
            {{- end }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "unified.name" . }}-configmap
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          command:
            {{- range .Values.worker.command }}
            - {{ . | quote  }}
            {{- end }}
          args:
            {{- range .Values.worker.args }}
            - {{ . | quote  }}
            {{- end }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
