{{- if .Values.worker.enabled }}
{{- if .Values.worker.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "worker.name" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.worker.autoscaling.scaledObject.enabled }}
    {{- include "keda.annotations" . | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    {{- if .Values.argoRollouts }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ include "worker.name" . }}
    {{- else }}
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "worker.name" . }}
    {{- end }}
  minReplicas: {{ .Values.worker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.worker.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.worker.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.worker.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.worker.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.worker.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}